mdn/developer-portal

Dockerfile

I fairly certain https://github.com/mdn/developer-portal/pull/3 did not mean to remove the `Dockerfile`, so I'm adding it back.

recover inadvertently deleted Dockerfile

---

developerportal/apps/health/tests/test_views.py
developerportal/apps/health/urls.py
developerportal/apps/health/views.py
developerportal/settings/base.py
developerportal/urls.py

This PR adds health-check endpoints, as well as their tests, for when the application is deployed within a Kubernetes cluster.

add health-check endpoints for kubernetes

---

Dockerfile
Jenkinsfile
developerportal/settings/base.py
docker-compose.yml
dockerfiles/Dockerfile.static
requirements.txt

Changes to support stage/production deployments.

improvements for production

---

k8s/Makefile
k8s/README.md
k8s/app.deploy.yaml.j2
k8s/app.env.yaml.j2
k8s/app.svc.yaml.j2
k8s/config/stage.sh
k8s/db-migration-job.yaml.j2
k8s/wait_for_job.sh

These are the initial Kubernetes-related files required for deploying the Developer-Portal CMS.

initial kubernetes-related files

---

developerportal/apps/staticbuild/management/commands/build-portal.py
developerportal/settings/base.py
docker-compose.yml

This PR adds a special `build-portal` Django management command and makes some adjustments to existing files.

add build-portal Django management command

---

k8s/Makefile
k8s/app.deploy.yaml.j2
k8s/app.pv.yaml.j2
k8s/app.pvc.yaml.j2
k8s/config/stage.sh

Allows sharing of media files between pods

Added a shared volume folder

---

developerportal/apps/people/templates/people.html
developerportal/templates/organisms/filter-list.html
src/css/organisms/homepage-header.scss
src/css/organisms/pattern-section.scss

* Tightens up padding after chats with Dan.
* Adds authors to cards within the article directory page.
* Ensure the spacing between newsletter and article directory section is correct.

Various design tweaks

---

developerportal/settings/production.py

Add SECURE_SSL_REDIRECT to production settings (#22)

---

docker-compose.yml

remove restart:always in docker-compose

---

developerportal/apps/people/templates/person.html
developerportal/apps/topics/templates/topic.html

* Remove events.all from templates for person and topic.

Fix events not showing for person and topic pages.

---

developerportal/apps/articles/templates/article.html
developerportal/templates/molecules/article-author.html
developerportal/templates/molecules/article-details.html
developerportal/templates/molecules/resource-topic-tags.html
src/css/global/variables.scss
src/css/index.scss
src/css/molecules/article-authors.scss
src/css/molecules/resource-toolbar.scss
src/css/molecules/resource-topic-tags.scss

Adds topic tags, share links, and details about the authors under the article body.

Updates to article template

---

developerportal/apps/home/templates/home.html
src/css/molecules/card.scss
src/css/molecules/external-promo.scss
src/css/organisms/filter-list.scss
src/js/index.js
src/js/organisms/filter-form.js
src/js/polyfills.js
src/js/utils.js

- Layout and JS on directory pages
- Layout for card container

WIP: IE fixes

---

.github/pull_request_template.md

Removing "issue" from "Resolves issue #XX" makes GH trigger auto-closing of the issue.

Update pull-request template wording re auto-close

---

k8s/app.env.yaml.j2

(Resolves #255)
- Exposes a `REDIS_URL` environment variable

Exposes REDIS_URL as a environment variable

---

developerportal/templates/molecules/card-featured-primary.html
developerportal/templates/molecules/card-featured.html

This changeset fixes an incorrect external item check for featured card icons.

Use correct check for icons within featured items

---

developerportal/apps/people/models.py
developerportal/templates/organisms/topic-links.html

This changeset changes the copy of the topics heading within the person profile page.

Change topics heading on person page

---

src/css/molecules/header.scss
src/js/atoms/map-embed.js

This changeset reverts a change in protocol‘s *mzp-c-menu* component styles which added bolding to menu items.

Revert menu weight change

---

README.md
docs/automatic-publishing-to-s3.md

There are still things that are TBD, but this gets it moving.

Add initial doc explaining how the static site will be generated.

---

k8s/Makefile
k8s/celery.yaml.j2

Adds celery worker pods
(Resolves #267)
- Adding celery worker pods

Adding celery workers

---

k8s/celery.yaml.j2

Fixing a typo

---

Jenkinsfile
scripts/slack-notify.sh

Adds slack notifications to developer-portal jenkins builds
(Resolves #55)
- Adding slack notifications for the jenkins build pipeline

Add slack notifications for the jenkins build

---

developerportal/apps/events/templates/events.html
developerportal/templates/organisms/featured.html

Fix bug in featured events by reusing feature layout
(Resolves #403)

Fix bug in featured events by reusing feature layout

---

developerportal/templates/404.html
developerportal/templates/500.html
developerportal/templates/footer.html
developerportal/templates/header.html
developerportal/templates/wagtailadmin/base.html
src/css/atoms/typography.scss

This changeset addresses some of the points raised from #354 
- Use the same font-display value as MDN
- Add nofollow noopener to external links

Lighthouse audit tweaks

---

k8s/config/prod-oregon.sh

Initial work to start getting prod config up on the repo
(Partially Resolves #100)
- Setups k8s config for prod

Adding prod config file

---

k8s/app.svc.yaml.j2
k8s/config/stage-oregon.sh
k8s/config/stage.sh

Updating certificate ARN for ELB and also adding additional Tags for ELB

Update cert arn to point to new cert

---

Jenkinsfile

Fixing some slack message so that it display the cluster it deploys to, also 
fixed a typo that causes the code to not get pushed to a cluster

Append cluster names as well as fixing a typo

---

developerportal/settings/base.py

This changeset addresses the needs to make logging config more explicit AND silence a single, particular kind of logged warning that's saturating the inboxes of `settings.ADMINS`: `django.core.exceptions.DisallowedHost`
* Rather than extend `DEFAULT_LOGGING` in our `settings.base`, show an explicit `LOGGING` config (based initially on the content of `DEFAULT_LOGGING`)
* Add a `null` handler / blackhole 
* With the blessing of @limed, use that `null` handler to trap all logger calls for `DisallowedHost`, which are drowning us. There's precedent for this approach, including [the official docs](https://docs.djangoproject.com/en/2.2/topics/logging/#django-security) and other, solid, Django sites like [readthedocs](https://github.com/readthedocs/readthedocs.org/pull/4879/files).
Note that …

705: Tune logging config

---

developerportal/templates/footer.html

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeveloper.mozilla.com%2F#vnuId11
> Error: Duplicate attribute rel.
> At line 787, column 98
> e-content/" rel="nofollow noop
Fix invalid HTML
Rerun https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeveloper.mozilla.com%2F

Fix repeated rel attribute in footer

---

developerportal/apps/common/tests/test_app_tags.py
developerportal/templatetags/app_tags.py

Small bit of housekeeping
* Fix typo
* Downgrade to DEBUG, to make it less chatty in the logs
(Resolves #950)

950: Tweak the logging in the cachebreaker app tag

---

package-lock.json

This updates node packages that hopefully will update `serialize-javascript`, I ran the following command to update `package-lock.json`
```
npm audit
npm audit fix
```
(Related issue #975)
- Update node packages

Update npm modules

---

Jenkinsfile
k8s/config/dev.sh
k8s/jenkins-rbac.yaml

Add dev environment

---

Jenkinsfile

Fixes a typo which pushes dev to the wrong location

Fixing jenkinsfile to point dev push to the proper location

---

developerportal/apps/bakery/tests/test_views.py
developerportal/apps/bakery/views.py
developerportal/apps/staticbuild/wagtail_hooks.py
developerportal/apps/taskqueue/__init__.py
developerportal/apps/taskqueue/celery.py
developerportal/apps/taskqueue/models.py
developerportal/apps/taskqueue/tasks.py
developerportal/apps/taskqueue/tests/test_tasks.py
developerportal/apps/taskqueue/tests/test_utils.py
developerportal/apps/taskqueue/tests/test_wagtail_hooks.py
developerportal/apps/taskqueue/utils.py
developerportal/apps/taskqueue/wagtail_hooks.py
developerportal/settings/base.py
docker-compose.yml
docs/cdn-invalidation.md
k8s/celery-beat.yaml.j2
k8s/celery.yaml.j2

This changeset complements the work in #945 to move to a dynamically rendered site.
It addresses the need to stop the CDNed content from getting stale by triggering invalidations at two key points. This invalidation is taken care of by a background Celery task.
* 942: Start laying in a new app for Celery tasks, for any new non-static-build tasks we need 
* 942: Add in background task to invalidate CDN + trigger it on Page publish/unpublish
* 942: Add a scheduled Celery task that invalidates the CDN for certain sections of the site
* 942: Fix ref to scheduled task in Celery queue -- bring it up to date with new location of that func
* 942: Ensure boto3 is initialised from settings over env vars
* 942: Remove scheduled tasks related to static-site publishing to reduce noise
* 942: Add light …

942: Update CDN invalidation triggers

---

Jenkinsfile
k8s/Makefile
k8s/config/dev.sh
k8s/config/prod.sh
k8s/config/stage.sh
k8s/hpa.yaml.j2

Configures horizontal pod autoscaler for wagtail
(Related issue #954)
- Sets up HPA during deployment process

Sets up HPA for wagtail deployment

---

k8s/config/prod.sh
k8s/config/stage.sh

Update cert arn to use a different cert

Cert arn update

---

docs/deployed_environments.md

… and how to get code up on them.
Resolves #1082

Add documentation to make it clearer about the three environments 

---

k8s/app.svc.yaml.j2

Enable the cross zone load balancing option on the ELB
This changeset addresses ... by ...
(Related issue #1247 )
- Add annotations to enable cross zone load balancing

Enable cross zone load balancing

---

package-lock.json

Second try of fixing security related packages, not sure why first npm audit didn't fix it
- Updating acorn npm package

Security fix part deux

---

package-lock.json

Updates minimist npm package again
- Minimist npm security updates

Update minimist npm package

---

developerportal/apps/externalcontent/wagtail_hooks.py

This changeset improves the UX of managing `ExternalContent` (eg the `ExternalArticle`s which are automatically generated from site feed)
* Limit page size to speed up performance
* Default to most-recently-edited first
* Add ordering column/control
- Code is on dev for test driving
## Screenshot

1400: Improve behavour of ExternalContent administration

---

Jenkinsfile

Addresses a bug I introduced in PR #1445, so I'm fixing the way
slack_notify is being called

Fixing slack messaging

---

developerportal/apps/events/templates/events.html

1671: Reword 'Featured events' to just 'Featured' on Events page

---

k8s/Makefile
k8s/config/prod.sh

Increase prod web pods hpa and also rework Makefile targets, rework of PR #1697 
(Related issue #1609)
- Increase max prod web pod  from 8->10
- Rework Makefile targets to allow more flexibility in the future

Increase max pod for web pods

---

docs/deployed_environments.md

Single character change to fix Markdown formatting

Fix header formatting on deployment docs

---

k8s/Makefile

Sets new image for redirector service, see https://github.com/mdn/infra/pull/459 for more details

Setup redirect for dev-portal
