mdn/developer-portal

developerportal/settings/dev.py, developerportal/settings/production.py
When using the `production` settings, set `ALLOWED_HOSTS` from `BASE_URL`. Also removes unused import in the `dev` settings.
=> set ALLOWED_HOSTS from BASE_URL in production

setup.sh
https://github.com/mdn/developer-portal/pull/9 modified, among other things, `setup.sh` to use `docker-compose pull` instead of `docker-compose up --build --detach`. This PR reverts that specific change. The problem is that `docker-compose pull` doesn't pick-up immediate changes that affect the build, like changes to `requirements.txt`, and so breaks CI testing (see https://github.com/mdn/developer-portal/commit/db00d2beb626d474c499dea985fbe5dfdc704403#r34155570).
=> revert back to build instead of pull in setup.sh

Jenkinsfile
This PR fixes a bug where the commands after `docker-compose -f docker-compose.test.yml up --detach` were not using the same docker-compose file.
=> explicitly specify the docker-compose file

k8s/app.env.yaml.j2, k8s/config/stage.sh
This PR adds the configuration for the stage S3 bucket used when using django-bakery's `./manage.py publish` command on the stage instance.
=> add aws bucket config for bakery publish command

developerportal/settings/base.py
This adds what I forgot to include in https://github.com/mdn/developer-portal/pull/24, the `AWS_BUCKET_NAME` to the Django settings.
=> forgot to add AWS_BUCKET_NAME to settings

developerportal/settings/base.py, k8s/app.env.yaml.j2, k8s/config/stage.sh
This PR adds the `AWS_REGION` Django setting for django-bakery's `publish` command. It's the region of the S3 bucket that's the target of the `publish` command.
=> add aws region for django-bakery publish

package-lock.json
Updating to a newer version of lodash due to CVE-2019-10744. I ran  the
following command to update
```
$ npm audit
$ npm audit fix
```
=> Updating lodash package

developerportal/urls.py
This is a temporary workaround, ideally media should be served by a static server.
=> Tweak urls to serve media in production.

developerportal/apps/articles/models.py
Caused by `topic_pks` sometimes containing Topic instances instead of pks.
=> Prevent 500 error when previewing article page

.github/pull_request_template.md
Tiny PR to add an initial pull-request template as per https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository. 
Why? Just makes it easier to start thinking about what to write in a PR
Resolves #141
=> 141: Add simple pull request template

.isort.cfg
This changeset remedies a blocker when using `therapist`, due to a duplicated line in the isort config, so it fails to run.
- removes duplicated `skip` key
=> Hotfix: remedy duplicated entry for `skip` in isort config

k8s/Makefile
This changeset addresses a typo in the Makefile which cause a persistent
volume and persisten volume claim to not be able to delete
- Added "pv" and "pvc" keyword in makefile to actually allow deletion to
happen
=> Fixing a typo in makefile

requirements.txt
Reverts mdn/developer-portal#163 -- 0.12.3 is a fixed requirement of wagtail-bakery, so better to wait for the upgrade to be led by that. I'll open an issue over there to check.
=> Revert "Update dependency django-bakery to v0.12.7"

requirements.txt
Because of:
> ERROR: wagtail 2.6 has requirement beautifulsoup4<4.6.1,>=4.5.1, but you'll have beautifulsoup4 4.8.0 which is incompatible.
Was 4.6.0 originally, going with 4.6.1 instead
=> Downgrade Beautiful soup from 4.8.0

requirements.txt
Effectively reinstating pre-renovatebot version to silence compat grumbles from `pipdeptree`
=> Further downgrade beautifulsoup

.therapist.yml
* Flip ESLint to whitelisting not blacklisting files (so just feed it .js files for now)
* Exclude webpack config from prettier's reach
=> Updates to tune Therapist

developerportal/apps/articles/models.py, developerportal/apps/common/forms.py, developerportal/apps/common/tests/test_common.py, developerportal/apps/common/wagtail_hooks.py, developerportal/apps/content/models.py, developerportal/apps/events/models.py, developerportal/apps/home/models.py, developerportal/apps/people/models.py, developerportal/apps/topics/models.py, developerportal/apps/videos/models.py
This changeset addresses the (minor) risk of somoene accidentially creating `wagtailcore` migrations that then could block an upgrade.
The root seems to be that attempting to patch `SomePageModel.some_field.help_text` at runtime is will change the underlying `Page` class definition by the time the migrations inspector reaches it, triggering the creation of a false/bogus migration.
(Resolves issue #136 )
I tried patching at the `FieldPanel` level, as done elsewhere in the project for the a `label`, but it turns out (confirmed by a core Wagtail dev in the project Slack) that `help_text` is not currently patchable. Instead, using a base form class became the next workable approach.
Python tests passing. Also added a light test to prove that the update to help_text works.
Manually checked, …
=> 136: Fix inappropriate creation of wagtailcore migration

renovate.json
This change [adds a "renovate"][1] label to new PRs to help with filtering
[1]: https://docs.renovatebot.com/configuration-options/#labels
=> Add label to renovate PRs

k8s/Makefile, k8s/app.env.yaml.j2
This change allows us to configure django to send email, the username
and password has been configured under k8s secrets and we expose a
couple of settings to allow django to relay mail via amazon SES
(Resolves issue #201)
- Exposes some email environment variables that django needs to send
email
=> Setup email environment variables

developerportal/apps/bakery/views.py, developerportal/settings/base.py, developerportal/settings/dev.py
This changeset deals with the need for an application-level redirect from HTTP to HTTPS without causing a redirect loop.
It also enables all-but-one of the recomended Django security settings as defaults (HSTS being the exception.)
It also deals with a regression that occurs with wagtail-bakery when that SSL redirect is enabled.
When deployed, it should resolve issue #22.
- **Enable recommended-by-Django security settings as defaults**
The base settings now follow all-but-one of the recommendations from manage.py `check --deploy`.
The only one that's not been done in this changeset is SECURE_HSTS_SECONDS, because of the risk of "serious, irreversible problems". That needs to be planned in to enable it properly.
Note that we're explicitly setting what HTTP header to look for to detect the …
=> 22: Enable SSL redirect and other security settings

k8s/app.env.yaml.j2
This sets a default from address for the django app
(Resolves issue #201)
- Expose DEFAULT_FROM_ADDRESS as an enviroment variable, and the value
gets pulled from k8s secret
=> Added default_from_address

developerportal/apps/common/feed.py, developerportal/apps/common/fixtures/common.json, developerportal/settings/base.py, developerportal/templates/404.html, developerportal/templates/500.html, developerportal/templates/header.html, src/css/molecules/header.scss
This changeset changes the site's name from Mozilla Developers to Mozilla Developer.
=> Update site name from "developers" to "developer"

developerportal/templates/molecules/card-featured-primary.html, developerportal/templates/molecules/card-featured.html
If an Article Page's detail and its Card detail both lack an image, there is no fallback image in use, so when the article is featured on the homepage, there is no image:
This changeset addresses that by using the standard article placeholder image.
(Closes #225)
- Use the standard placeholder image when nothing better is available.
Note that the 960px-wide image is used for both the 480w (card-featured.html) and 1024w (card-featured-primary.html) use-cases, because we can't create Wagtail renditions of images that are not known of in the database. I am assuming likelihood of a primary-featured article lacking an image is low, so I think we can make do with 960px being upscaled to 1024px, partic as the 960px may already be cached. If I'm wrong, we can add a 1024px version to …
=> 225: Ensure Homepage-featured Articles have fallback images

developerportal/settings/base.py, developerportal/settings/production.py, developerportal/templates/atoms/social-meta.html, developerportal/templates/header.html, developerportal/templatetags/app_tags.py, k8s/Makefile, k8s/app.env.yaml.j2, k8s/config/stage-oregon.sh, k8s/config/stage.sh
This changeset (when combined with a correct configuration for Site.hostname in Wagtail) fixes the issue where the static/baked site was linking back to live wagtail CMS instead of to itself.
The previous swing at this (#195) ~was too complex, and~ had a shortcoming, so I closed it.
Closes #133
--
**Changes:**
* Removed the use in templates of a `base_url` value that points to the Wagtail CMS. This now means that the URLs in any page (live-on-Wagtail or "baked") are relative rather than absolute, which means they are always appropriate for the site being browsed, whether it's the live Wagtail-hosted one or the S3-hosted baked site.
* In addition, for the moments where the hostname _is_ required to build an absolute URL, the main `Site.hostname` value should be set to the URL of the site …
=> 133: Address problem of static/S3-site URLs linking back to Wagtail live views

developerportal/templates/molecules/card-featured-primary.html, developerportal/templates/molecules/card-featured.html, src/css/molecules/card-featured.scss
This changeset adds external icons to the headings of external featured cards on the home and topic pages, making it easier for a user to identify that they'll be leaving the site.
- Add icon to headings of external cards.
- Add one or more external featured items to either home or topic pages.
=> Add external icons to external featured cards

developerportal/settings/dev.py
These changes are needed to allow a user to log in locally on a non-HTTPS setup
=> Hotfix: downgrade some production security settings for local dev

developerportal/templates/molecules/article-author.html
This changeset addresses a bug where the "see more" link in external author article descriptions would render, even when no URL was supplied.
- Conditionally render the "see more" author link on articles, hiding when no URL is present.
- Add `target` and `rel` properties to the link when it's an external URL.
- Set an article to have an external author without setting a URL. The link shouldn't render.
- Set the external author's URL to a test URL. The link should open in a new tab.
=> Only show "see more" link when a URL exists

developerportal/templates/molecules/article-details.html, src/css/molecules/article-details.scss
This changeset addresses a bug in the author details section where separators were not being added when external authors were present. This changeset fixes the issue by ensuring the separators are added _after_ an external author conditional, and also adds support for multiple overlapping avatars when more than one author is present.
Before:
After:
- Ensure separator is added after external author conditional.
- Add overlapping avatars when more than one author is present.
- Add multiple authors to an article and ensure the author details section handles these correctly.
=> Fix author separators and support multiple avatars

developerportal/settings/base.py, k8s/Makefile, k8s/app.env.yaml.j2
This changeset addresses the lack of being able to send a password reset email on staging by plugging in the now-available email config vars from the environment.
(Resolves #201)
- Add `APP_` prefix to env var definitions for consistency
- Enable emailing for deployed site by pulling through the env vars that have been set up already.
Note that `DEFAULT_FROM_EMAIL` uses an address which has been verified with SES, so there should be no sending issues.
If you have SMTP credsits to hand (eg, extract your Gmail ones), you can test the email sending config is correct at the CLI.
- check out the branch locally
- add/edit `settings/local.py` to set `EMAIL_BACKEND` to `'django.core.mail.backends.smtp.EmailBackend'` (because it's set to `ConsoleBackend` in `settings/dev.py`
- add the required …
=> 201: Enable email on staging

developerportal/templates/molecules/card-featured-primary.html, developerportal/templates/molecules/card-featured.html
This changeset fixes a bug within the icon logic, meaning external resources are now catered for (not just single-use, external links) in featured items.
=> Handle external resource icons as well as links

developerportal/apps/home/templates/home.html, developerportal/apps/topics/templates/topic.html, developerportal/templates/organisms/featured.html
This changeset uses the filtered list of items (i.e. `page.featured|published`) when working out the number of featured items.
=> Use filtered items for featured count

developerportal/apps/bakery/tests/test_views.py, developerportal/apps/bakery/views.py, developerportal/settings/base.py
This changeset adds a custom view which is used by wagtail-bakery (django-bakery
really) to set up AWS S3 Webpage Redirects[1] based on any configured Wagtail
Redirects for the default Site or for all Sites.
Once all the regular pages have been published to S3, the new view triggers the
creation of the appropriate S3 Website Redirects. wagtail-bakery/django-bakery
also takes care of tearing down existing redirects before re-adding them. (Note
that these redirects may remain cached by a browser, so if a redirect is removed
from Wagtail and removed from S3, some users may still see the redirection
happen until their browser invalidates the cache, which may be never unless
it's manually zapped.)
[1] (https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html)
(Resolves #264)
- …
=> 264: Support automatic creation of S3-side redirects based on Wagtail  Redirects

k8s/app.env.yaml.j2
Exposes cloudfront CDN ID, the value is in k8s secret store
(Resolves #293)
- Exposes cloudfront distribution ID
=> Expose CDN distribution id

src/css/molecules/card.scss
This changeset addresses a bug where the two card layouts would break. This was after IE-specific fixes were added recently, breaking the card layouts on some pages.
Before:
After:
=> Ensure two card layout works after IE fixes

docker-compose.yml
Remove port 8080 for the `docker-compose` file, exposing this port causes issues with tests since jenkins runs on port 8080
(Resolves part of #316)
- Remove port 8080 for the `docker-compose` file
=> Removing port 8080, this port is used by jenkins

developerportal/apps/home/templates/home.html, developerportal/apps/people/models.py, developerportal/apps/people/templates/people.html, developerportal/apps/topics/models.py, developerportal/apps/topics/templates/topic.html, developerportal/templates/organisms/people-section.html
This change set adds a ‘Recent authors’ section to the People directory page as per the latest designs. These people are pulled in dynamically based on recently published articles.
- Add ‘Recent authors’ section to the People page.
- Add ‘People’ section to the home page.
- Refactor section with circular profiles to reusable organism.
- Create a new article, assign one or more authors and publish.
- The author(s) should appear at the top of the People directory page.
=> Add ‘Recent authors’ section to People directory

src/css/molecules/item-person.scss
This changeset adds a width to the people images to ensure they fit their containers, even when images with smaller dimensions are uploaded. By default, Wagtail won't upscale images – so when images are smaller than intended, they often break layouts.
We have recommended guidelines for images, but this is mainly to prevent the layout from breaking.
=> Fix image sizes when small media is uploaded

.isort.cfg, Dockerfile, developerportal/apps/staticbuild/__init__.py, developerportal/apps/staticbuild/celery.py, developerportal/apps/staticbuild/tests/test_auto_build.py, developerportal/apps/staticbuild/wagtail_hooks.py, developerportal/settings/base.py, developerportal/settings/dev.py, developerportal/settings/test_fast.py, docker-compose.yml, requirements.txt
Contains PRs #325 and #336 so we can deploy them together
-----
* Initial steps moving automatic generation and upload of the static site to a queue-managed background task.
Changes include:
* Update Dockerfile to:
- rename `app` target as `app_base`, to make it clearer it's being used for multiple things
- not start gunicorn as part of `app_base`'s build, because that's not needed and is handled by docker-compose or k8s
* Update docker-compose.yml to:
- add `redis` container
- update the `app` config to inherit from a new `common` config, which uses the `app_base` target
- add new `worker` container, inheriting from the `common` config, too
* Add `celery` to the project
- Stop the use of `subprocess.Process` when a page is published or unpublished.
- Use a a properly enqueued task to …
=> Integration PR: pulling together the Celery work

Jenkinsfile
We have 2 clusters at the moment, this change removes the need for the EKS cluster temporarily. The end goal is to use the EKS cluster at some point but we don't want to push changes there via CI atm.
- Dont push CI changes to EKS cluster
=> Don't push changes to eks cluster

k8s/Makefile, k8s/app.efs-setup.yaml.j2
This PR adds a k8s job that will create and chown the media directory. By default all folders get created with `root:root` permission, our containers run with GID and UID 1000 so this job fixes that. This job should only be needed once
(Resolves #340)
- Add k8s job and Makefile targets to fix permission of media files
=> Add k8s job to set media permissions

developerportal/settings/base.py
Intended to be combined with configuration, this changeset partially addresses the need for a 404 page available in the S3-served website.
(Resolves #287)
- adds a special view to the `django-bakery` pipeline that renders out the 404 page. It's output to the root of the build dir as `404.html`
- Pull this branch
- Shell into the running `app` container (`docker-compose exec app /bin/sh`)
- Run a build: `./manage.py build`
- View the output 404 file: `less /app/build/404.html`
=> 287: Build a 404.html page during generation of the static site

k8s/celery.yaml.j2
The celery workers need to have the attachments mounted for it to be able to build the static content this PR mounts the volumes into the pod
(Resolves #341)
- Mount dev portal attachment EFS to celery worker pod
=> Mount dev-portal attachments onto celery nodes

k8s/app.env.yaml.j2, k8s/config/stage-oregon.sh, k8s/config/stage.sh
This changeset exposes the `AWS_STORAGE_BUCKET_NAME` variable to the developer portal app which will help facilitate uploads of user media and get us away from using EFS
(Resolves #317)
- Expose storage bucket name
=> This commit exposes an s3 bucket that will host user uploaded media

developerportal/apps/videos/models.py
This change set addresses the 500 that occurs when trying to preview a Video with a Topic set.
The error occurs in the Video.related_resources method. Article has the same method with different logic, so I’ve copied that approach.
(Resolves #359 )
=> Prevent 500 error when previewing a Video page associated with a Topic

README.md, developerportal/settings/base.py, developerportal/settings/dev.py, developerportal/settings/local.py.example, developerportal/templatetags/app_tags.py, requirements.txt
This changeset enables the use _in production_ of `django-storages` to use AWS S3 for custom files/images uploaded into Wagtail, rather than store them in the local filesystem. (Local dev's default remains the same.)
Note that these user-media files go to a DIFFERENT S3 bucket from that configured for holding the baked-out static site.
When a site is built that features S3-hosted images, there is no need to download them only to upload them to the static-site bucket - the HTML and CSS just reference the images in the S3 user-media bucket instead. (It would be good to CNAME this user-media bucket at least - that's ticketed in #318)
This changeset also introduces a template for local settings that make it easier to develop S3-related behaviour while in local development mode (ie, reinstate …
=> 265: Support uploading user-media to AWS S3, instead of local filesystem

developerportal/templates/atoms/social-meta.html, developerportal/templates/base.html
This changeset adds support for default page meta descriptions by using the home page's `search_description` field value.
(Related to #354)
- Add default description to base template, using the home page's `search_description` field.
- Add a description to the `search_description` field on the home page and observe it added to all pages as the default meta description.
=> Use home search_description as default for pages

developerportal/templates/molecules/card-featured-primary.html, developerportal/templates/molecules/card-featured.html, src/css/molecules/card-featured.scss
This changeset addresses a bug where icons wouldn't wrap correctly in external featured items. This prevents orphaned icons when titles are a specific length.
Before:
After:
- Remove `inline-block` from incorrectly applied element within featured external items.
- Use different length titles within featured external items and test that no length will leave an external icon orphaned without a word.
=> Fix wrapping with external featured item icons

developerportal/apps/staticbuild/management/commands/enqueue_build_and_sync_task.py, developerportal/apps/staticbuild/models.py, developerportal/apps/staticbuild/wagtail_hooks.py
This changeset gives us a way to add a build-and-sync request to the Celery
queue, so that a cron-like job to republish the site every hour (for example)
will use the same path/behaviour as a regular Publish action.
Manually tested:
```
/app $ ./manage.py enqueue_build_and_sync_task
INFO:developerportal.apps.staticbuild.management.commands.enqueue_build_and_sync_task:Adding a build-and-sync request to the task queue.
INFO:developerportal.apps.staticbuild.management.commands.enqueue_build_and_sync_task:Build-and-sync added to task queue.
```
And in the worker:
```
worker_1  | [2019-10-10 15:48:47,155: INFO/MainProcess] Received task: developerportal.apps.staticbuild.wagtail_hooks._static_build_async[93cd46e4-65e1-4be2-8b46-19135d454bd4]
worker_1  | [2019-10-10 15:48:47,156: …
```
=> 296: Add management command to add a build-and-sync task to the task queue

developerportal/apps/staticbuild/tests/test_task_queue.py, developerportal/apps/staticbuild/wagtail_hooks.py, developerportal/settings/base.py
This changeset addresses the issue of Celery worker processes clobbering each other's output directories, resulting in imperfect syncs to S3. It deals with it by ensuring each enqeued job uses a unique (precisely timestamp-based) output directory to build to and publish from, before then deleting that output dir.
(Note that I'll probably add some locking to stop Celery wasting time on parallel builds of the _same_ task, so this is a stopgap, but it's good to keep things on the level.)
(Resolves #379)
- summarise changes here, linking to commits as appropriate
- Have the full local stack up, including Celery worker
- `docker-compose exec app python manage.py shell`
- `from developerportal.apps.staticbuild.wagtail_hooks import static_build`
- `for i in range(4): static_build()` (then double …
=> 379: Add and use a temporary subdir of BUILD_DIR when baking a site

developerportal/apps/people/templates/person.html, src/css/global/section.scss
This changeset ensures that the "see more" links in some section headers wrap correctly on mobile devices.
Before:
After:
- Wrap "see more" links in section headers on mobile devices.
- Remove "see more" link from profile article section (since it was deemed not to make sense).
- Test that section header wraps correctly on small device sizes.
=> Fix "see more" link wrapping and remove from profiles

developerportal/apps/events/models.py
Small changes to Event page admin to bring editor experience in line with other page models.
(Resolves #378 )
- Move event details and venue address fields to content tab
=> Move event details and venue address fields to content tab

Jenkinsfile
Fixes a logic error that causes jenkins to notify even when tests passes
(Resolves #55)
- Added a `catch` block
- Sneaked in a notify when tests are sucessful
=> Fix some logical error that causes slack to notify even when tests pass

developerportal/apps/common/utils.py, developerportal/apps/events/models.py, developerportal/apps/events/templates/events.html, developerportal/templates/organisms/event-speakers.html, developerportal/templates/organisms/filter-list.html, developerportal/templates/organisms/past-events.html, src/js/atoms/toggle.js
This changeset adds a "past events" section to the events directory page, allowing users to see historical events and view their respective singular pages.
Screenshot of upcoming/past events sections:
- Add a "past events" section to the events directory page.
- Adjust heading structure within directory page to accommodate multiple event lists.
- Fix button hiding bug within toggle component.
- Ensure past events are within the system.
- Observe that a "past events" section displays correctly within the events directory page.
- Ensure that after three past events, a "see all" button appears and more events are shown after this button is clicked.
=> Add past events section to events directory

requirements.txt, scripts/ci-setup
There are certain conditions that we run into that causes ci jobs fail
and its generally caused by either the database not being ready or a
permission denied error, which to me indicates that the old credentials
are still lingering after a job completes.
This commit hopes to fix that by using the `urlwait` tool to wait for
the database instance to be up and running as well as additional steps
in there that will go ahead and cleanup the environment before a build
and run.
(Resolves #389)
- Add `urlwait` tool as a requirement
- Remove `.env` file if it exists
- Ensure that there are no running containers when `docker-compose` up gets run
- Add wait conditions in `ci-setup` script
- From base directory run `scripts/ci-setup --build` and wait for build to complete
- Run `scripts/ci-tests` …
=> Fixes certain race conditions on the ci test jobs

k8s/config/stage-oregon.sh, k8s/config/stage.sh
Simplifies the name of the s3 bucket, currently its using the convention of `developer-portal-<environment>-<account id>`, this PR moves the media bucket to a different bucket that has a shorter name
(Partially Resolves #318)
- Rename media bucket
=> Rename media bucket

docker-compose.yml
(Resolves #370)
- Improve syntax of docker-compose.yml to define `common` outside of the `services` node so that it doesn't get built and run as a container
* `docker-compose build && docker-compose up` and then `docker-compose ps`
**Before:**
```
$ docker-compose ps
Name                         Command               State           Ports
-------------------------------------------------------------------------------------------
developer-portal_app_1      gunicorn developerportal.w ...   Up      0.0.0.0:8000->8000/tcp
developer-portal_common_1   python3                          Up      8000/tcp
developer-portal_db_1       docker-entrypoint.sh postgres    Up      5432/tcp
developer-portal_redis_1    docker-entrypoint.sh redis ...   Up      6379/tcp
developer-portal_static_1 …
```
=> Update docker-compose.yml to not make and run a redundant 'common' container 

.isort.cfg, developerportal/apps/common/settings_helpers.py, developerportal/apps/common/tests/test_regex.py, developerportal/apps/common/tests/test_settings_helpers.py, developerportal/apps/staticbuild/celery.py, developerportal/apps/staticbuild/context_managers.py, developerportal/apps/staticbuild/management/commands/enqueue_build_and_sync_task.py, developerportal/apps/staticbuild/tests/test_auto_build.py, developerportal/apps/staticbuild/tests/test_task_queue.py, developerportal/apps/staticbuild/wagtail_hooks.py, developerportal/regex.py, developerportal/settings/base.py, developerportal/settings/dev.py, developerportal/settings/test.py, developerportal/settings/test_fast.py, docker-compose.yml, k8s/celery.yaml.j2, requirements.txt, scripts/ci-tests
If merged, this changeset addresses the need to avoid concurrent and therefore conflicting builds being processed by the task queue.
It does this by switching from a pattern where builds are immediately enqueued (and picked up by workers) to one where builds are idempotently _requested_. A periodic task checks each minute if a build is needed and, if so, performs it.
(Resolves #279 - and goes beyond this, because it became clear it was necessary)
-  Refactor how we enqueue jobs in Celery, to avoid concurrent builds and race conditions
Prior to this commit, if a flurry of build requests were issued (eg multiple authors publishing)
this would put N jobs in the queue. Celery is configured by default to use the number of cores
on its worker node, so this would mean 4 (or more) builds taking …
=> 279: Re-architect how we're using our task queue to avoid concurrent builds

k8s/celery-beat.yaml.j2
celery-beat doesn't like the `--concurrency` option, removing this to allow celery-beat to start up
- Remove `--concurrency` option
=> Remove concurrency option for celery beat

developerportal/apps/staticbuild/celery.py, docs/automatic-publishing-to-s3.md
This changset adds a regular task to the Celery Beat scheduler that requests a fresh static build at 30 mins past each hour.
Note that it only requests a build, rather than starts one, so that this doesn't risk causing concurrent builds. It slots neatly into the existing pattern.
At startup can see the job being registered:
```
scheduler_1  | <ScheduleEntry: fresh-static-build-every-hour developerportal.apps.staticbuild.wagtail_hooks._request_static_build() <crontab: 30 * * * * (m/h/d/dM/MY)>
```
And at that point in time you can see the job requesting a new static build:
```
scheduler_1  | [2019-10-22 12:46:00,000: INFO/MainProcess] Scheduler: Sending due task fresh-static-build-every-hour (developerportal.apps.staticbuild.wagtail_hooks._request_static_build)
```
...which gets handled as …
=> Automatically request a fresh static-site rebuild each hour

Jenkinsfile, k8s/config/prod.sh
This PR deploys developer-portal to 2 clusters (our existing KOPS cluster and an EKS cluster), however the only difference is that one of the cluster will not have any `celery-beat` and `celery-worker` pods running.
(Resolves #453)
- Create config for a second cluster
- Update `Jenkinsfile` to deploy to another cluster
=> Deploy to 2 clusters

k8s/app.env.yaml.j2
This is a counter part PR for #401 in which we expose the auth0 `client_id` and `client_secret` for SSO integration.
(Partiall Resolves #474)
- Expose auth0 `client_id` and `client_secret`
=> Add auth0 client id and client secret

developerportal/apps/staticbuild/celery.py, developerportal/apps/staticbuild/wagtail_hooks.py
While not all of the publishable objects in the CMS use Wagtail's go-live/de-publish
dates, some of them do (the External* entities, basically).
We should support this behaviour in case editors expect something to happen based
on the options available to them.
This changeset adds a periodic celerybeat task that calls Wagtail's
`publish_scheduled_pages` management command once an hour, at five mins before
the hour.
(Resolves #436)
Here's an example of it running at a (test) 29 mins past the hour:
```
worker_1     | [2019-10-28 17:29:00,039: INFO/MainProcess] Received task: developerportal.apps.staticbuild.wagtail_hooks._publish_scheduled_pages[333407c9-9f7a-4427-8ed0-00d3fb908fce]
worker_1     | [2019-10-28 17:29:00,043: INFO/ForkPoolWorker-4] [Static-build-and-sync requester] Trying to …
```
=> 436: Support Wagtail's scheduled publishing behaviour via periodic task

developerportal/templates/molecules/card-featured-primary.html
This change alleviates repetition on pages where there's also a H2 saying "Featured" just above this card.
(Resolves #550)
## Before
=> 550: Remove 'Featured' wording from the primary featured card

developerportal/apps/articles/models.py
This changeset addresses the risk of an over-long and messy filter list on the articles page by removing the option to filter articles by month
(Resolves #548)
----
----
----
=> 548: Disable filtering of articles by month

developerportal/templates/organisms/newsletter-signup.html, src/css/organisms/newsletter-signup.scss
This changeset addresses poor visibility of the privacy-policy link in the footer. By using a light blye from Mozilla Protocol's colour options, it now 
(Resolves #551)
=> 551: Make the privacy policy link in the footer more prominent

developerportal/settings/base.py
This changeset addresses the problem of non-unique filenames overwriting an existing file of the same name when uploaded to S3 via `django-storages`.
Enabling `AWS_S3_FILE_OVERWRITE=False` means that filenames that would otherwise clash are renamed with a unique suffix.
See https://docs.wagtail.io/en/v2.6.3/advanced_topics/deploying.html#cloud-storage for the background
(Check out the resulting filename, not the image's name) 
-----
-----
=> Ensure that files uploaded to S3 that have the same filename do not clash

developerportal/settings/base.py
This changeset addresses a request from MozInfoSec to try enabling HTTP-only CSRF cookies.
Talking with `@gasmanic` (Lead Wagtail dev), it sounds like Wagtail doesn't do
anything that should be affected by enabling this, but we should still keep
an eye open.
A light test-drive locally seemed fine and the content-entry phase we're entering will be a good shakedown.
(Resolves #615)
=> 615: Enable HTTP-only cookies for CSRF

developerportal/settings/base.py, developerportal/settings/dev.py
This changeset enables HSTS by setting a default time of 1 hour for the Strict-Transport-Security
header, which we can upgrade to a year (31536000 seconds) once we're happy.
(Resolves #604)
Note that the default behaviour for ALL non-local-development mode is to
have HSTS **ENABLED**, so staging WILL be affected, too.
Also, note that the SECURE_HSTS_INCLUDE_SUBDOMAINS setting is NOT set, so it
remains its [default value](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-SECURE_HSTS_INCLUDE_SUBDOMAINS) of `False`. This is because Django warned (via
`manage.py check --deploy`) to: 
> ...only set this to True if you are certain that all subdomains of your domain should be served exclusively via SSL. 
and I don't know what else goes on `mozit.cloud` or `mozilla.com` so am …
=> 604: Enable HSTS by default

developerportal/templates/base.html
This changeset prepares the ground for switching the Google Analytics ID from staging to production, so there will (normally) be no GA ID configured. In that situation, we want to avoid including any GA code, rather than risk it complaining in the console. 
(Resolves #591)
- Only load GA code if Google Analytics ID is available
```
...
</footer>
<script>window.Mzp = {}</script>
<script src="/static/js/bundle.js"></script>
</body>
</html>
```
```
...
</footer>
<script>window.Mzp = {}</script>
<script src="/static/js/bundle.js"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-[REDACTED]-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-[REDACTED]-1');
</script> …
```
=> 591: only load GA code if Google Analytics ID is available

developerportal/templates/atoms/social-meta.html, developerportal/templatetags/app_tags.py
An earlier changeset introduced overly-simplistic behaviour when trying to create absolute URIs for images while also using S3 storage. Its logic was: "If we're using S3, we don't need to make the URLs for images in the OG tags absolute because they already will be absolute". 
This worked as long as there **was** a deliberately-associated image to use, but failed when there was not one set up and so a fallback image was used instead. This is because these fallback images are served by Django and have relative paths, not absolute ones.
This changeset addresses that with different, and clearer, conditional logic
Examples from `view-source`
```
<meta property="og:title" content="Events">
<meta property="og:site_name" content="Mozilla Developer">
<meta property="og:image" …
```
=> 609: Fix incorrect solution to juggling absolute and relative URLs in OG tags

developerportal/settings/base.py
This changeset configures who should be emailed if if ERROR or above is raised within Django.
* the `mail_admins` option is in the default config (which we are extending, not overwriting) - see [here](https://github.com/django/django/blob/stable/2.2.x/django/utils/log.py#L55)
* @limed has set up an email group (`dev-portal-errors@mozilla.com`) in #621, which is set as the only address in `settings.ADMINS`
This is hard to test, so I rigged a the homepage to `raise Exception("test")` then loaded it. So here's an example of this working (locally, with the `console` `EmailBackend`):
```
app_1        | Content-Type: text/plain; charset="utf-8"
app_1        | MIME-Version: 1.0
app_1        | Content-Transfer-Encoding: quoted-printable
app_1        | Subject: [Django] ERROR (EXTERNAL IP): …
```
=> 622: Enable settings.ADMINS so we get basic error-report emails

developerportal/apps/people/models.py, developerportal/apps/people/templates/people.html
This changeset removes the unit at the top of the People page that showed the three authors with most recently published things.
**BEFORE:**
**AFTER** (different data, because rendered locally, and using fallback/placeholder images, which are all unrelated to the changes made here)
The unit is gone, and we've added in a new 'People' `h2`, in the same position as the `h2` on 'Articles'. 
This changeset also drops now-rendant code from People page model that generated that list of latest authors.
(Resolves #567)
=> 567: Remove 'Latest authors' section from top of People page

k8s/config/prod-oregon.sh, k8s/config/prod.sh
Increases the number of `celery-workers` and `web` nodes for the prod
environment.
(Resolves #523)
- Increase number of pods for celery and web pods
=> Increase number of pods for prod

developerportal/templates/molecules/card-featured.html
(Because there's a h2 saying the same word just above)
Resolves #648
=> 648: Drop 'Featured' wording from inside cards that are featured

developerportal/apps/staticbuild/celery.py, developerportal/settings/base.py, developerportal/settings/build.py, developerportal/settings/worker.py
This changeset catches a subtle one: we don't want the live-rendered pages (eg someone previewing a draft page or viewing a live page on the CMS domain) to show up in Google Analytics.
Happily, because we now omit the GA JS if we have no GA ID available via settings, we can address this easily enough:
* Remove code from `settings.base` that gets the GA code from the env
* Add a new `settings.worker` module, which DOES try to get the GA code from the env
* Ensure Celery is using that new `settings.worker` module, so that it's the only place where the GA code is obtained and, therefore, used.
GA code present in ENV but page live-rendered by CMS:
```
</footer>
<script>window.Mzp = {}</script>
<script src="/static/js/bundle.js"></script>
</body>
</html>
```
GA code present in ENV and page …
=> 642: Only insert the Google Analytics code into the static site

developerportal/apps/common/helpers.py
The ExplorerRedirectAdminURLHelper helper class is used via wagtail_hooks.py to send people
to a list of children for a given 'first-class' page (Articles, Videos, Events, Topics). 
However, the helper only checks the DB at the point of startup. So, if a page which uses this helper is added or recreated AFTER that point, the changes won't be reflected until server restart. The most likely manifestation of this is when setting up a new deployment from scratch and you see `/admin/None` for the sidebar links
This changeset adds this info as a docstring, where it would be have saved me an hour if it had existed already 😉 
It also adds some logging, to make it easier to catch this in Production if we roll out a new type of Page
=> 669: Add docstring to make it easier to know how to solve broken new sidebar links

developerportal/settings/base.py
Uses a sensible default of the DEFAULT_FROM_EMAIL, but can be explicitly set if need be.
(Resolves #672)
=> 676: Add SERVER_EMAIL configuration

developerportal/templates/robots.txt, developerportal/urls.py
We don't need any of the Wagtail-rendered pages (CMS or published pages) to be picked up by spiders
(Resolves #672)
=> 672: Add block-all robots.txt

developerportal/apps/staticbuild/wagtail_hooks.py
When DEBUG=True, the static build is always skipped, but - in this case - the worker was still making a temporary build path (even though it wasn't being used to make a directory). 
In turn, the presence of the build_path var, but no actual directory of that name, was then
causing `shutil.rmtree` to error out, understandably.
This changeset addresses that by only generating the build path if we're not in debug mode.
(The default value for the build path is None.)
Example output:
```
worker_1     |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1     |     R = retval = fun(*args, **kwargs)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
worker_1     |     return …
```
=> Fix up minor static-pipeline bug in local development when DEBUG=True

k8s/Makefile, k8s/app.env.yaml.j2, k8s/celery.yaml.j2
This changeset allows `DJANGO_SETTINGS_MODULE` to be a configurable value, this is a companion PR of https://github.com/mdn/developer-portal/pull/684
- Set a default value `DJANGO_SETTINGS_MODULE` in the `Makefile`
- Export `DJANGO_SETTINGS_MODULE` in the `Makefile` target of your choice to select the value you want
=> Make DJANGO_SETTINGS_MODULE configurable

developerportal/apps/common/migrations/0001_drop_social_auth_app_tables.py
...now that it has reached (and been run on) production.
If someone happens to still have the social-auth tables locally, that's not a great concern.
A fresh install will match the state of stage/prod.
It's good to tidy this up now in case we re-add python-social-auth (or its family members) to the project and wonder where our DB tables went during CI 😄 
Run locally to check that it can be applied forwards and backwards with no effect:
```
Operations to perform:
Unapply all migrations: common
Running migrations:
Rendering model states... DONE
Unapplying common.0001_drop_social_auth_app_tables... OK
/app $ python manage.py migrate common
Operations to perform:
Apply all migrations: common
Running migrations:
Applying common.0001_drop_social_auth_app_tables... OK
```
(Resolves #475)
=> 475: Disable the migration that drops the social-auth tables

developerportal/settings/base.py
This has been done to reduce the risk of long-open CMS pages failing to save,
because of CSRF issues. (See the comment in the diff for more.)
=> Increase length of the OIDC 'lease' time

developerportal/apps/externalcontent/wagtail_hooks.py
This changeset fixes an issue where draft pieces of ExternalContent were not visible in the Admin, which then can cause a server error when the user tries to add the same information again (with the same resulting slug, which causes a 500).
By ensuring the ExternalContent views show both live and draft states, we can avoid this.
Examples of the updated UI:
(Resolves #718)
=> 718: Make it possible to see draft ExternalContent in the Admin

developerportal/apps/articles/models.py, developerportal/apps/articles/templates/articles.html, developerportal/apps/common/feed.py, developerportal/apps/common/tests/test_feed.py, developerportal/apps/videos/models.py, developerportal/settings/base.py, developerportal/templates/base.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/molecules/cards/card.html, developerportal/templates/organisms/filter-list.html
This changeset slightly changes the direction of what will soon (via #624) be the Posts page.
It will contain data from Article Pages and also Video Pages. The retrieval of those
was already handled by a helper function, but the HTML templating and JS form-filter
code needed a small update.
Note that while I think this change has no adverse side-effects, there may be a regression somewhere due to the various ways some of the molecule templates are re-used - we should keep a close eye open during content entry.
(Resolves #625)
- add some videos
- give at least some of them topics (via the meta tab)
- view the /articles/ page (soon to be /posts/) and confirm you can see the videos in with the articles
- confirm the filtering works as expected to show/hide the videos and related articles
=> 625: Allow posts/articles page to also show videos

Dockerfile, docker-compose.yml
Currently our CI server uses port 80 to do a reverse proxy to the jenkins (we do ELB SSL termination at the ELB level). However for local development we started exposing port `80` and port `443` (see PR #424) which causes jenkins to fail so this change removes port `80` from the nginx container since realistically we only want to test SSL anyway. 
Sneaked in a couple of cleanup changes that came from PR #424, we no longer need openssl and bash installed on the `app` container
- Remove port `80` from `nginx` container
- Cleanup packages we don't need
- Run `docker-compose up -d --build` locally, and test `https://developer-portal-127-0-0-1.nip.io` responds
- Chicken and egg situation where this PR needs to be merged to ensure that jenkins actually completes a build
=> Remove port 80 from nginx service, sneeaked in some cleanup as well

Jenkinsfile, docker-compose.yml
Ensures that GID and UID is set for the `cfssl` container, this ensure that Jenkins eventually owns the cert files
(Resolves #753)
- Sets `GID` and `UID`
=> Set GID and UID for cfssl container

k8s/Makefile
Set `NEW_RELIC_APP_NAME` to emptry string for db migration job since it doesn't need it.
=> Set NEW_RELIC_APP_NAME to emptry string in migration job

developerportal/apps/staticbuild/models.py, developerportal/apps/staticbuild/wagtail_hooks.py
The `force` keyword hasn't been supported for a few weeks (since the refactor to the 'request a build' pattern from the 'start a build' one). This changeset removes the keyword and adds a clearer message hinting at how to get a statid build running locally:
```
worker_1     | [2019-11-11 16:30:30,265: INFO/ForkPoolWorker-3] [Static-build-and-sync] Attempting fresh build
worker_1     | [2019-11-11 16:30:30,266: INFO/ForkPoolWorker-3] [Static-build-and-sync] (wagtail-bakery) command 'Build' skipped because DEBUG=True.
worker_1     | [2019-11-11 16:30:30,267: INFO/ForkPoolWorker-3] [Static-build-and-sync] (wagtail-bakery) command 'Publish' skipped because DEBUG=True.
```
It also rephrases the Admin menu item from 'trigger' a static build to 'request' one
While manually QAing this, I …
=> 747: Cleanup static build process to remove `force` keyword

developerportal/settings/base.py
This changeset addresses the desire for smaller page loads, by implementing gzip compression for the pages generated by `wagtail-bakery`
It's simple configuration tweak, plus some tidying up of nearby settings.
HOWEVER, before we merge this, we need to be 100% happy that it's not going to be at risk of [BREACH](http://breachattack.com/) or similar attacks. (For now the site is entirely inert/GET-only, but we shouldn't assume this makes it automaticall OK - a check in with MozInfoSec is worthwhile.)
UPDATE: checked MozInfoSec and got a 👍 
(Resolves #691)
=> 691: Enable gzip compression for HTML pages

developerportal/apps/common/tests/test_app_tags.py, developerportal/templates/molecules/filter-form.html, developerportal/templatetags/app_tags.py, src/js/utils.js
This changeset addresses two small niggles with the filter form:
1) Only show a Clear All option when there is more than one group of filters available on the page
2) Fix an issue to do with form filter state set up from querystring parameters.
(Resolves #651)
- **Fix showing the 'X Clear all'  trigger when there is only one filter to clear**
**"Clear all" present when multiple filter groups exist**
----
**"Clear all" absent when just one filter group exists**
----
----
-  **Fix issue with JS filter-form**
Prior to this changeset, when pages were loaded with a querystring for selected filters (eg a user back-arrows from a page, or gets sent a URL), there was a bug where unselecting one of the checkboxes would actually add it to the querystring again (eg `?topic=foo,bar` --> …
=> 651 Fix glitches with topic filters

developerportal/apps/common/forms.py, developerportal/apps/common/tests/test_common.py, developerportal/apps/externalcontent/models.py
This changeset addresses a blow-up when adding External entities (any subtype) that has a name that auto-creates a slug that matches an existing slug for another piece of `External[Content|Video|Article|Event]`.
(For context an `External[Content|Video|Article|Event]` is still a subclass of a Wagtail `Page`, but when it is used we never render it as a regular Wagtail page: we just use it as a way of holding data about an external URL to load.) 
Prior to this changeset, because the `slug` field for the entity was not surfaced in Wagtail's Admin UI, there was no way to catch and report a slug-field clash as a `ValidationError`, so the conflict would cause an integrity-related blow-up during `save()`. (The slug field was probably not shown, because an `External*` item isn't meant to be used …
=> 726 Surface hidden slug clashes for external content

k8s/app.deploy.yaml.j2, k8s/celery.yaml.j2
Start `gunicorn` and `celery` using `newrelic-admin` this will allow them to start sending metrics over to New Relic
(Resolves #758)
- Start up app using `newrelic-admin`
=> Start celery and gunicorn using newrelic-admin

developerportal/settings/base.py
An earlier changeset (for #691) enabled gzip compression during the wagtail-bakery build process. However we now have that as part of the CDN configuration so only enabling it in ONE place makes sense.
(Resolves #777)
=> 777: Disable gzip of content by django-bakery

src/css/organisms/filter-list.scss
The `+` and `X` no longer feels offset vertically. Also tried to equalise the space towards the right box border, too.
(Resolves #784)
=> 784: improve padding for the filter-list open/close trigger on mobile

src/css/molecules/item-topic-link.scss
While this isn't a perfect fix, it makes the content less susceptible to reflow issues triggered by differing widths of the SVG icons for each Topic. Note that the existing SVG icons do not need to be changed for this to be "good enough" (See comments in #781), but standardising them will also help.
Checked locally and/or in Browserstack across Edge, FF, Safari and Chrome
(Resolves #718)
=> 781: Minor CSS changes to Topic blocks to better align the rich text

k8s/Makefile, k8s/db-backups-cron.yaml.j2
This changeset creates a cronjob that runs daily and creates a daily db dump of the database. The db dump is encrypted using a passphrase and then uploaded to `s3`
(Resolves #802 )
- Create k8s cronjob to run a nightly db dump on the prod database
=> Add db backup cron

developerportal/apps/bakery/views.py, developerportal/apps/externalcontent/models.py, docs/developer-notes.md, requirements.txt, src/js/utils.js
Somewhere between wagtail-bakery 0.3 and 0.4 (which was recently bumped as a dependency) a change took place that surfaces a shortcoming in our code: ExternalContent subclasses return None for .get_site() because they are not saved as children of Articles, Videos or Events, respectively.
The workaround for now is to just get the default Site for these Pages. A fuller fixup has been ticketed as #865.
Note that bumping django-bakery in this changeset didn't cause the regression - it was happening before that, and this change is just to bring it up to date, now that wagtail-bakery==0.4.0 allows a higher version of django-bakery.
I've also added a reminder to the developer notes about the downside of assuming we can always use the default Site if we lack a route to a Page's actual Site. …
=> 864: Fix regression with static-site generation

developerportal/apps/bakery/tests/test_views.py, developerportal/apps/bakery/views.py, developerportal/settings/base.py, developerportal/templates/base.html, developerportal/urls.py
This changeset adds an XML sitemap to the rendered site and also includes it in the static site exported to S3
(Addresses #746)
- locally, run `docker-compose exec app manage.py build` to "bake out" the static site to `/app/build/` in your `app_1` container
- shell in with `docker-compose exec app sh` 
- `less /app/build/index.html` to see the link to `sitemap.xml` in the `<head>` of the document
- `less /app/build/sitemap.xml` to see the sitemap content itself.
For convenience, I've temporarily exposed my own dev S3 bucket in website mode, so you can check for yourself. The content is dummy, but the sitemap is still correct. (Note that there is no HTTPS on this example bucket)
- View source on http://devportalstatictestxyz.s3-website-eu-west-1.amazonaws.com/ - see that the sitemap is …
=> 746: Add sitemap support to static site

k8s/app.env.yaml.j2
Exposes the `SENTRY_DSN` to kubernetes, the sentry dsn is the public dsn
only so if the secret key is needed we can change that in the secrets.
(Related issue #803)
- Set `SENTRY_DSN` in pod envvars
=> Expose SENTRY_DSN

developerportal/templatetags/app_tags.py
This changeset ensures all randomly generated hashes start with an `a` and are still 16 chars long.
There's no risk of collision because we're extending the original hash, rather than swapping out the
first (random) char for a fixed on.
This avoids validator.w3.org/nu reporting an error such as:
`Bad value 72644ef3cd99e4c20245b864b1ff1cb2-a for attribute id on element path: Not a valid XML 1.0 name.`
In addition to this change, we'll need to manually edit the WebAssembly SVG icon to fix duplicate IDs in the SVG markup (which isn't in this codebase)
No unit tests, but manually tested
(Related issue #825)
=> 825: Address SVG-related validation errors due to invalid hashes as ids

developerportal/templates/molecules/event-details.html
The use-case here is an Event in multiple places, where a single country cannot be configured. If there is no Venue address specified (eg for a multi-country roadshow) then prior to this changeset an empty UI element with a Location icon but no data would be rendered.
This changeset now makes that conditional: we only show the Location icon and row if there is data to populate it.
This changeset also includes showing the name of the venue in the location bar - it was previously only shown around the map box 
(Resolves #885 )
=> 885: Ensure that if an Event has no Venue address specified, don't show an empty location row

developerportal/settings/base.py, requirements.txt
Automatically enabled when SENTRY_DSN is available as an env var
Supoprts the idea of a REVISION_HASH as per Kuma, but I don't know if it's available (but it would be nice to add)
(Resolves #803)
Tested locally using staging credentials, sending from both the test management command and by raising an exception in a Celery task (to prove we'll get alerts from the worker, too):
=> 803: Add Sentry support

k8s/Makefile, k8s/app.env.yaml.j2
This changeset addresses our need to increase the HSTS lease time now we're in production. It does this by defining config for a one-year-long lease in seconds, and exposing that as an env var
(Resolves #882 )
=> 882: Increase HSTS lease time to 1 year, via env vars

developerportal/templates/footer.html
The original request (see #577) was to link to Mozilla's mission. Sense-checked where to place this link with Havi, who suggested we actually link to the About page, because that puts the Mission front and centre, in context.
She also suggested we add the Community Participation Guidelines, so I have.
~Note: the existing footer links all have `nofollow` in them -- is this someting we definitely want?~
(Resolves #577)
=> 577: Update footer to link to Mozilla info and Community Guidelines

developerportal/apps/common/tests/test_app_tags.py, developerportal/templates/atoms/social-meta.html, developerportal/templatetags/app_tags.py
This changeset adds and uses a new template filter that, for a given URL, checks if it has a cachebreaking hash and if it does, converts it to be a URL that uses the hash as a querystring cachebreaker instead.
eg:
INPUT: 'https://example.com/static/foo.12313abc.jpg'
OUTPUT: 'https://example.com/static/foo.jpg?h=12313abc'
Why? So that images automatically embedded in social media posts (via OpenGraph tags) don't end up as broken links with a new release that changes the hash in the filename -- by moving the hash to a querystring, we get the benefit of cachebreaking but with a much softer edge that won't result in links 404ing even if the cachebreaking hash has changed. (ie, querystring cachebreakers are more forgiving.)
Note that `ManifestFileStorage` (used by `django-whitenoise` in this …
=> 886: Add template filter to move the cachebreaker string from inside the filename to a querystring

developerportal/settings/base.py, requirements.txt
This changeset addresses the risk of a user breaking SSO for the CMS should they change their email address in the system. It achieves this by upgrading to Wagtail 2.7 ([release notes](https://wagtail.readthedocs.io/en/v2.7/releases/2.7.html)) and making uses of its new `WAGTAIL_EMAIL_MANAGEMENT_ENABLED` setting.
BEFORE
AFTER
(Note that Admins can still change email addresses for users via `Settings` > `Users` in the CMS admin)
I've been through the [Upgrade Considerations](https://wagtail.readthedocs.io/en/v2.7/releases/2.7.html#upgrade-considerations) and I think we don't need to change anything. However, it is worth noting that the [UI for StreamFields](https://wagtail.readthedocs.io/en/v2.7/releases/2.7.html#what-s-new) is revised in this release. There's not much we can doto avoid …
=> 469: Upgrade to Wagtail 2.7 and prevent users amending their email addresses

developerportal/templates/base.html, developerportal/templates/base_includes/google_analytics.html, src/js/head-includes.js, src/js/mozilla-dnthelper.js, webpack.config.js
This changeset moves away from using GTM and instead drops in GA code in the head of the document, as per mdn/kuma
At the same time it also uses the same Do Not Track lib [that kuma uses](https://github.com/mdn/kuma/blob/master/kuma/static/js/libs/mozilla.dnthelper.js) - thanks @sneethling!
Note that the DNT lib lifted from kuma is slighty changed to pin a `Mozilla` object on the DOM's `window` so that it's within reachable scope within the page. The way Kuma integrates the same code is to inline it into the HTML (ie, render it as a template) but that behaviour isn't currently supported by the Developer Portal codebase, and switching to it seemed more disruptive than just updating webpack to output a new bundle.
As before, if there is no `GOOGLE_ANALYTICS` code present via settings, the …
=> 906: Switch from Google Tag Manager to regular GA; add in Mozilla DNT support

requirements.txt
There were too many stale Wagtail-specific dependencies in the lower part of the requirements.txt file, which meant that some things that should have been upgraded for wagtail 2.7 were not. (This was surfaced by Willow 1.1 still being present, and lacking a feature that Wagtail 2.7 expected, causing server errors.)
By removing the "subdeps" from requirements.txt wherever possible, we get a clean install.
The things that HAVE changed now are:
* modelcluster==5.0
* django-taggit==1.2.0
* python-dateutil==2.8.0  # down from 2.8.1 which helps with boto compat
* Willow==1.3
Note that beautifulsoup is pinned to the range that Wagtail needs, because readtime tries to get a newer, incompatible-with-Wagtail version
=> Update requirements to fix regression when we moved to Wagtail 2.7

developerportal/templates/organisms/newsletter-signup.html
This changeset addresses a request to improve the wording of the newsletter call to action, as requested by @havi 
(Resolves #962)
=> 962: Small but important wording improvement in newsletter signup CTA

developerportal/settings/base.py, developerportal/settings/worker.py
Prior to this changeset, we only included the Google Analytics code/JS in static pages, so
that we didn't end up having data beign sent from both the dynamic/CMS pages and also the
static ones.
This changeset updates the settings so that we get/use Google Analytics in all situations,
not just the static-site generation.
This changeset addresses ... by ...
(Resolves #938)
- add `GOOGLE_ANALYTICS=testcodehere` to your .env file and down then up your docker stack
- View source on any page - it will (unless you have DNT enabled...) show GA JS, featuring `testcodehere`
=> 938: Ensure dynamic site renders out GA code

developerportal/apps/common/tests/test_utils.py, developerportal/apps/common/utils.py, developerportal/apps/events/models.py, developerportal/apps/events/tests/test_events.py, developerportal/apps/people/models.py, developerportal/apps/topics/models.py
This changeset adds a single source for the cutoff between past and future events, setting it to 'yesterday'
Prior to this changeset, the difference between future and past events is decided based
on datetime.datetime.now() which is likely to be UTC (given k8s), but regardless of what
specific timezone it is or is not, it still draws a single line "down the globe" that
means that, the further west of UTC you live, some events will 'disappear' from future
events before that day has completed.
The fix is simply to keep showing events as 'upcoming' until one calendar day *after*
their start date.
(Resolves #944)
- Add an Event with a start date that is yesterday's date
- On `master`, load the /events/ page and confirm you do not see the relevant Event, even though yesterday's date could …
=> 994: Update what counts as a future/past Event 

src/css/molecules/header.scss
This changeset fixes the reflow that occurs when the nav options are particularly numerous and/or long.
Basically, it makes the CSS for the largest viewport use the same, slightly reduced padding values as the next, smaller media query.
_Note that things **are** quite packed in now. If we can move About to the footer, regardless of this change, that would still be useful_
(Resolves #1011)
Take a look at https://developer-portal.dev.mdn.mozit.cloud/, which originally was like:
And is now
*Please have a play around with the viewport sizes by resizing your browser and trying to break the layout* 😄
=> 1011: Fix premature nav reflow issue 

k8s/app.deploy.yaml.j2
This addresses intermittent dns resolution issues reported by the pod. We set `ndot` to `1` so that the dns resolution will not iterate through the search domains.
(Related issue #1067)
- Configures `ndot` to `1`
=> Set ndots to 1

wagtail-rfcs/000-append-comments-for-moderation.md
Added initial technical specification section and tweaked a bit of the great initial spec
Some of the changes here are just down to auto-formatting from the code editor.
If/once this is ok we can merge it to `master` then submit it via pull request from a fork of `wagtail/wagtail`, as per the official guidance
(Related issue #872)
=> 872: Tweak and expand the RFC for content moderation messages

k8s/jenkins-rbac.yaml
Updated RBAC for jenkins user to now allow creation of HPA's
- Updated RBAC to allow creation of HPA
=> Update RBAC for jenkins

developerportal/apps/externalcontent/models.py
Prior to this changeset, the absence of a template for any subclass of ExternalContent (eg External Articles) meant that it was impossible to preview them. The template was never created because such pages are never rendered in the published site only linked to. The Preview aspect was not yet covered.
This changeset overrides the `serve_preview` view to simply redirect to the `external_url` configured for that page/item.
(Resolves #1097 )
No tests, but manually tested
=> 1097 - HOTFIX: Ensure that previewing an ExternalArticle does not 500

developerportal/apps/common/fixtures/common.json, developerportal/apps/common/models.py, developerportal/apps/common/tests/test_context_processors.py, developerportal/apps/common/tests/test_models.py, developerportal/apps/topics/models.py, developerportal/apps/topics/tests/test_topics.py, developerportal/context_processors.py, developerportal/settings/base.py, developerportal/settings/test.py, developerportal/templates/molecules/filter-form.html, developerportal/templates/organisms/topic-links.html
This changeset addresses the need to stop calling [most] things "Topics" and instead draws the phrasing to use from the current title of the `Topics` page. It does this in a way that minimises database hits just to get that display string.
(Related issue #1010)
- Update base/common fixture with new phrasing of Topics page title, for local consistency
- Add Python-layer support for dynamically using the title of the Topics page in rendered output:
* adding a context processor to make the Topics title string available in all templates
* added write-through caching behaviour to the above, so we don't hit the DB unnecessarily
* added cache invalidation via a 'bulk invalidate' approach: when a Topics model is saved, all its related/configured
cache keys are zapped
* tests for the above
- Use …
=> 1010 Make "Topics" phrasing dynamic

developerportal/apps/events/models.py, developerportal/apps/events/tests/test_events.py
This changeset ensure multiple Events in the same year-month combination don't cause the year-month values to appear multiple times in the filters. It adds a method to squash out the duplicates, with tests
(Resolves #1141)
**Before (example from prod)**
**After (example from local)**
=> 1141: Fix duplicated year-month filters in Events

developerportal/apps/articles/models.py, developerportal/apps/content/models.py, developerportal/apps/events/models.py, developerportal/apps/people/models.py, developerportal/apps/topics/models.py, developerportal/apps/videos/models.py
This changeset addresses the absence of the "Scheduled Publishing" fields on most of the pages in the CMS. They are now reinstated for all page types apart from the Homepage, including the 'grouping' pages like `Videos` and `Events`, not just `Video` and `Event`
This now matches default behaviour for Wagtail pages - there's nothing special to test, beyond confirming that the pages can be saved (which they can)
(Resolves #540)
It's up on the [dev environment](https://developer-portal.dev.mdn.mozit.cloud/admin/), but also here's a screenshot of what to look for:
=> 540: Reinstate scheduled publishing fields for all pages

developerportal/apps/common/tests/test_app_tags.py, developerportal/apps/common/tests/test_head_rendering.py, developerportal/templates/base.html, developerportal/templatetags/app_tags.py
This changeset helps stop robots indexing the dev or staging deployments.
It adds a `"noindex"` directive via a `<meta>` tag, but not on production.
Staging and Dev (and local dev):
Production - no tag present:
(Related issue: #1099)
- this one is more easily done via code review, but if you have it checked out locally, you can set `ACTIVE_ENVIRONMENT="production"` or `"staging"` or `"development"` in your `settings/local.py`
=> 1099: Add a "noindex" meta tag for robots - for Staging and Dev

developerportal/apps/content/models.py, developerportal/apps/content/tests/test_content.py, developerportal/apps/topics/models.py, developerportal/apps/topics/tests/test_topics.py
This will make the entire landing/products and technology heirarchy easier to set up the way we need.
A topic page now allows the addition of a Content Page as a child:
And the child page's URL path sits beneath that of the parent Topic page:
Please try it out on the dev server
https://developer-portal.dev.mdn.mozit.cloud/topics/test-topic/test-subpage-topic-page/
(Related issue #1203)
=> 1203: Allow Topic pages to have a ContentPage as their child page.

requirements.txt
This change set adds packages to support additiona; gunicorn worker_classes
(Related issue #1216)
- Installs `gevent`, `greenlet`, `gevent-socketio` and `gevent-websocket` python packages
=> Add additional packages to support other worker_classes in gunicorn

k8s/app.deploy.yaml.j2
This change set updates what gunicorn returns for its logs, specifically it now returns the referer and X-Forwarded-For header which is handy
(Related issue #1210)
- Update log format for gunicorn
=> Update log format for developer-portal

developerportal/apps/common/constants.py, developerportal/apps/common/wagtail_hooks.py, src/css/admin.scss, src/css/atoms/buttons.scss, src/css/index.scss, src/js/admin-extras.js, webpack.config.js
(Note: a big hat-tip goes to @kalobtaulien for his assistance with this, making it a much smaller change than writing an entirely new Draftail Entity. \o/ )
This changeset supports a way of marking certain links in a rich-text area as buttons, so that they are rendered as such in the published page.
(This should allow us to make pages that feature lots of buttons without the page becoming too heavy/complex, which appears to be a factor in editing hanging after a certain tipping point.)
It acheives this by adding a new button to the Draftail editor which adds a new block (a div, lightly styled with a dashed grey border) inside which one can add hyperlinks using rich-text editor's standard link button. Any links inside this block will be rendered as buttons in the published (and previewed) …
=> 1207: Add support for styling specified links as buttons in Wagtail's rich-text editor

src/css/molecules/notification-bar.scss
* rollover state for CTA link
* position of Close trigger
BEFORE
AFTER
=> 1237 Fix notification bar css glitch

package-lock.json
There are security vuln for the `acorn` and `minimist` packages, this
fixes it. For more info see CVE-2020-7598
- updating node packages to resolve security alerts
=> Resolving security alerts

Dockerfile, configs/gunicorn.py, docker-compose.yml
This moves the gunicorn config to a config file instead of calling
command line options. This will only affect local dev for now, and there
should be another PR to actually have kubernetes use the config file as
well
(Related issue #1213 & #1211)
- Moves gunicorn config to a config file
=> Move gunicorn config to its own file

k8s/app.deploy.yaml.j2
This PR switches the kubernetes deployment to use the gunicorn config
file which in turn switches the worker class to `gevent`
(Related issue #1195)
- Switches config to a config file
- Switches gunicorn worker class from `meinheld` to `gevent`
- You can test locally with `docker-compose`
=> Switch gunicorn worker class to gevent

developerportal/apps/articles/templates/articles.html, developerportal/templates/molecules/cards/card-article.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/organisms/filter-list.html
This changeset updates the design of the Posts page, building on patterns established elsewhere in the designs
(Related issue #1225)
- Staged on dev. Please check that internal links work and that external video and external article links also behave as expected. (External videos should play in a lightbox)
- Cross-browser testing welcome (but will be done later, too) 
----
-----
=> 1225: Update design of the Posts page

developerportal/templates/molecules/recent-work-item.html
This changeset ensures that any external videos mentioned in the 'recent work' section of the Topic page will open in a modal/lightbox, rather than taking the user to the third party site.
As part of this work, I also confirmed that external videos in the Posts list also play in a lightbox.
(Related issue #1271)
- Code is staged on dev.
- Check that in 'Recent work' on https://developer-portal.dev.mdn.mozit.cloud/topics/test-topic/ a lightbox is used to display the test video
- Also check the same happens for the video on the Posts page (currently listed as the first item)
=> 1271: Ensure external video on topic page opens in a modal

developerportal/apps/common/wagtail_hooks.py, developerportal/templates/atoms/icons/external.svg, developerportal/templates/molecules/card-featured.html, developerportal/templates/molecules/cards/card-article.html, developerportal/templates/molecules/cards/card-event.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/molecules/related-links.html, developerportal/templates/organisms/event-agenda.html, developerportal/templates/organisms/event-map.html, src/css/molecules/card.scss, src/css/molecules/related-links.scss
* Drop markup that includes the external.svg
* Drop related CSS
* Drop external.svg icon
(Related issue #1270)
- Staged on dev. Add an external video/post/event to a relevant page and you'll see you can still follow the link in a new tab as before, but you won't see the external icon any more
## Screenshots
Just an example...
**BEFORE**
**AFTER**
=> 1270: Stop marking external links with a special icon

developerportal/apps/articles/models.py, developerportal/apps/articles/templates/article.html, developerportal/apps/articles/templates/partials/verbose_standfirst.html, developerportal/templates/molecules/cards/card-person.html, developerportal/templates/molecules/header-strip.html, developerportal/templates/organisms/article-read-more.html, developerportal/templates/organisms/people-section.html, src/css/index.scss, src/css/molecules/header-strip.scss, src/css/molecules/item-topic-link.scss, src/css/organisms/article-read-more.scss, src/css/organisms/homepage-header.scss, src/css/organisms/people-section.scss, src/css/organisms/topic-recent-work.scss, src/css/templates/article.scss
This changeset lays in a new design for the Post/Article page.
(Related issue #1260)
A few niggles noticed, and all feedback welcome @malqinneh @valgrimm 
- the related article cards below show the full description of the page (default behaviour, and applies also to the Featured cards), so the page editor should configure a shorter "card description" (in the Card tab for the relevant linked pages). OR we don't include any description text.
- multiple authors make the page very busy!
- in general the author card image is quite large/dominating
- in mobile view, the authors sidebar could do with a header to explain it before you reach the pictures of the people, OR we just hide it entirely in mobile view
----
----
----
- summarise changes here, linking to commits as appropriate
- Staged on …
=> 1260: Single Post page refresh

developerportal/templates/header.html
This changeset addresses an issue with the navigation that meant the two sections with drop-downs were not accessible via keyboard navigation. 
They now are:
(Related issue #1312)
Code is deployed to the [Dev server](https://developer-portal.dev.mdn.mozit.cloud) (or you can check out this branch) Best to test this in Chrome or Safari if on a Mac as the Firefox needs some prodding to get it to behave the same way :)
- Go to the Dev site. 
- Click in the URL bar 
- Start tapping tab and keep tapping it.
- You will notice that focus for `Products & Technologies` and `Communities` is NO LONGER skipped
- Use Shift + Tab to cycle back if need be
- When `Products & Technologies` or `Communities` is highlighted, hit `Enter` to make the sub-section fold out. 
- Continue tabbing to see focus move …
=> 1312: Navigation accessibility fixup

package-lock.json, package.json, src/js/newsletter-subscription.js, src/js/polyfills.js, src/js/tests/newsletter-subscription.test.js
This changeset addresses functional failures in IE11 due to unsupported JS APIs
* Fix newsletter signup failure in IE11 due to lack of native browser support
* Add polyfill for `fetch` (which in turn required a `Promise` polyfill)
* Add workaround for absence of URLSearchParams in IE11 and a fully-featured FormDaga implementation - rather than adding yet more (large) polyfills, some more manual code was a more workable solution
* Add in Object.assign polyfill (from MDN docs) so that the light box will work for viewing external videos within the site in IE11
(Related issue #1233)
- Code will be staged on the dev server.  Using Browserstack please confirm you can:
* Sign up to the newsletter from the footer in IE11 and also in evergreen Firefox
* View an external video (see the one at the …
=> 1233  add ie11 polyfills

developerportal/apps/events/templates/event.html
And if an event has both a description AND body streamfield content, we show both, with a HR between them.
And if an event ONLY has body streamfield content set, we show that, with no HR
(Related issue #1461)
Code is staged on Dev - take a look at some events to:
**Description only present**
----
**Body streamfield only present**
----
**Both present**
=> 1461 FIX: Ensure that if an Event has a description, it is shown

src/css/templates/content-page.scss
This changeset fixes up the natural spacing on a `ContentPage` so that no hacks with `<br>` in HTML blocks are needed.
It puts a 48px margin below certain content blocks that are allowed in the `CustomStreamField` in the `ContentPage`
Blocks given spacing after them are: Paragraph, Image, Embed or Code snippet
The raw HTML block does NOT get automatic spacing - that seemed unnecessary
Note that it does NOT do this for `CustomStreamField` use anywhere else (eg on an Event page or similar) - that's something we can review as needed
(Related issue #1382)
**BEFORE**
**AFTER**
- Code is staged on dev. I had edited [this page](https://developer-portal.dev.mdn.mozit.cloud/admin/pages/379) to remove the HTML `br` blocks and to also put the H2 in the SAME block as the text which follows it (else …
=> 1382: Improve spacing after elements in a content page

developerportal/templates/atoms/social-meta.html, developerportal/templates/molecules/card-featured.html, developerportal/templates/molecules/cards/card-article.html, developerportal/templates/molecules/cards/card-event.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/molecules/image-block.html, developerportal/templates/organisms/article-header.html
This changeset brings the resizing rules left over from the original design into a better fit with the redesign, reducing the risk of fuzziness due to significant automatic resizing of images. It also takes into account the different needs of a 3:2 image compared to a 16:9 image.
It also makes the default width of an image in an image block wider, to suit the new use in the Content Page.
With the above, experiments showed that targetting precisely the exact rendered image dimensions (eg 771px wide for an image block in a Content Page) rather than a rounded, slightly larger number (eg 800px wide) led to the smaller image actually appearing fuzzier than the slightly larger image -- ie, the browser resize is better than a Wagtail hard resize. Given the relatively small file-size difference …
=> 1476: Review and adjust image-resizing directives

developerportal/templates/survey.html, src/js/task-completion-prompt.js
This small changeset contains two small fixes for low-grade things that came up via code review and testing:
* Add an accessible name to the "survey close" button
Hat-tip to @schalkneethling for the pointer
* Make the task-completion-cookie marker be `sameSite=strict` because there is no reason to send it to third parties
Code is staged on [Dev](https://developer-portal.dev.mdn.mozit.cloud/) server
=> 1467 small tweaks

requirements.txt
We now use gevent with gunicorn instead of meinheld, so this dependency can be dropped from our requirements
=> 1484: Drop Meinheld dependency

src/css/molecules/header.scss
Previously, the logo was being shown as if stacked below the hamburgr icon. In fact, had desktop-specific margin-top on it which we correct in this changeset. Indeed, the change is to introduce a negative margin because the CSS in the Mozilla Protocol design system expects use of a single black-bar Mozilla logo, not a composite Mozilla Developer logo.
Some explicit-width-sizing work was also needed to make Safari render the logo in the right place. This does not affect desktop layout behaviour.
Cross-browser checked in Browserstack for iOS Safari on XS and iPhone 11; Chrome and FF on Pixel 4, plus PC and Mac evergreen desktop Chrome, FF, Edge and IE11, as appropriate
Resolves #1496
- Code is staged on [dev](developer-portal.dev.mdn.mozit.cloud/) server
=> 1496: Improve position of Mozilla Developer logo for mobile viewport

developerportal/apps/articles/models.py, developerportal/apps/externalcontent/models.py, developerportal/apps/taskqueue/celery.py, developerportal/apps/taskqueue/tasks.py, developerportal/apps/taskqueue/tests/test_tasks.py, developerportal/apps/videos/models.py, developerportal/settings/base.py
This changeset lays in groundwork for adding Search to the Posts page.
It: 
1) Enables the Postgres search backend for Wagtail (which is recommended for sites with fewer than 1m pages and straightforward search requirements). It is set to automatically update the search index, and to do so atomically, so that search is always available
2) Adds configuration to the relevant Page subclasses that appear on the Posts page so that `wagtailsearch` knows to index them (and which fields on them to index)
3) Add a scheduled task, as per Wagtail recommendations, to fully rebuild the search index (again, atomically) once a week
- Unit tests have been added, and for now this is probably best just code reviewed, as subsequent PRs will build on its functionality, making manual testing much easier. …
=> 1510: Make "Posts"-page content indexable for Wagtail search

developerportal/templates/molecules/header-strip.html
This changeset avoids including an empty div.standfirst-wrapper, because it comes with bottom padding that we don't want when it has no content
Before fix
After
Before fix
After
After fix - pages with standfirst still have sensible padding
And pages with deliberately no standfirst have sensible padding
- Code is on [Staging](https://developer-portal.stage.mdn.mozit.cloud/) - please confirm that these all look fine/better
* https://developer-portal.stage.mdn.mozit.cloud/posts/
* https://developer-portal.stage.mdn.mozit.cloud/posts/test-page-search/
* https://developer-portal.stage.mdn.mozit.cloud/events/
* https://developer-portal.stage.mdn.mozit.cloud/events/developer-roadshow-2019-asia/
* https://developer-portal.stage.mdn.mozit.cloud/communities/people/
* …
=> 1556: Remove unnecessary padding in header strip

developerportal/apps/events/models.py, developerportal/apps/externalcontent/models.py
This changeset extends the default indexing of `Event` and `ExternalEvent` pages beyond just `Page.title` to include additional fields from the models:
* `Event` -> `title`, `description` and `body` fields
* `ExternalEvent` -> `title` and `description`
(Related issue #1534)
- nothing to test yet, because this is only configuration -- just a quick eyes-over code review os enough. We'll prove these work as part of backend Events search behaviour
=> 1534: Add slightly customised search indexing of Event and ExternalEvent

Jenkinsfile, k8s/Makefile, k8s/README.md, k8s/search-index-update-job.yaml.j2
This changeset adds k8s deployment config to rebuild search index after deployment.
This is so that if the changeset being deployed contains changes to the search index (including deploying search to production the first time) we need to make sure the index is ready.
It needs to follow after migrations have been completed, because the `wagtailsearch` app itself has migrations.
- summarise changes here, linking to commits as appropriate
- This isn't staged yet - for now code review is enough, then after that I will try deploying it to staging. It won't hit production until the related Epic is ready for launch in a couple of weeks' time, but I will ship it to dev and staging before then
=> 1546: Trigger Wagtail's search index rebuild on deployment

k8s/Makefile, k8s/db-backups-cron.yaml.j2
This changeset changes the RDS Cronjob to use Amazons IAM Roles for Service account, you can read more about this here https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/
Related PR: https://github.com/mdn/infra/pull/437
Related Issue: #1578 
- Replace AWS IAM Access keys with Roles and utilize AWS EKS IAM Roles for Service Accounts
- Apply kubernetes manifest
- Run a kubernetes job manually by running the command `kubectl create job --from=cronjob/dev-portal-rds-backups test`
=> Update cronjob to use IRSA

developerportal/apps/articles/models.py, developerportal/apps/common/constants.py, developerportal/apps/content/models.py, developerportal/apps/events/models.py, developerportal/apps/externalcontent/models.py, developerportal/apps/home/models.py, developerportal/apps/ingestion/tests/test_utils.py, developerportal/apps/ingestion/utils.py, developerportal/apps/people/models.py, developerportal/apps/topics/models.py, developerportal/apps/videos/models.py
This changeset increases the amount of information we use from RSS and Atom feeds when automatically creating `ExternalArticle` and `Video` draft pages, respectively.
In both formats, It looks for a `description` element in the output of the feed parser and, if it contains a `<p>` node, uses that as the `description` field for the page that is auto-created.
Note:
* If there is more than one `<p>` node in the parsed input's `description`, it uses only the first  one
* If there is no `<p>` node, the `description` is not used at all
* If there is a `<p>` node but its contents are longer than 393 characters (ie, the 400 max limit, minus seven characters for `<p>` and `</p>` tags, the content is truncated inside the `p` node is truncated, **so descriptions MUST be read before the page is …
=> 1514: Ingest descriptions from feeds where possible

developerportal/apps/articles/templates/articles.html, developerportal/apps/common/constants.py, developerportal/apps/common/tests/test_app_tags.py, developerportal/apps/events/templates/events.html, developerportal/apps/people/templates/people.html, developerportal/templates/molecules/filter-form.html, developerportal/templates/molecules/pagination.html
This changeset adds a change that takes the user to the top of the results list when they "Refine Results" on any page that features the filter form.
(Pagination already did this, so it made sense to also have Refine Results land users on the same part of the page, especially because the default view of an Events page focuses on featured content, not results.
(Related issue #1581)
- Code is deployed on [staging](https://developer-portal.stage.mdn.mozit.cloud/)
- Please check filtering and pagination (you may need to deselect filters to get enough content) takes the user to the top of the results:
- https://developer-portal.stage.mdn.mozit.cloud/posts/
- https://developer-portal.stage.mdn.mozit.cloud/events/
- https://developer-portal.stage.mdn.mozit.cloud/communities/people/
I think the …
=> 1581: improve the UX of refining a view of Posts, Events or People 

developerportal/apps/events/models.py
A pretty small change because everything 'just works' based on the development done for the filter form as part of adding Search to the Posts page
- Code is on [staging](https://developer-portal.stage.mdn.mozit.cloud/events/) - please try it out, including confirming script injections (eg `<script>alert("injected!");</script>` do not get executed
=> 1531: Add Search input to the Events page

Jenkinsfile, k8s/Makefile
Test kubernetest manifest before deploying, utilizes kubeval which has been installed on the CI server
(Related issue #697)
- Added tests for deployment to test if k8s manifest is valid
- Install [kubeval](https://github.com/instrumenta/kubeval) on your local machine 
- Source config file
```
cd k8s
source k8s/config/${dev,stage,prod}.sh
```
- Run make file to run test
```
cd k8s
make test-k8s-deployments
```
=> Added a test target to test k8s manifest

developerportal/apps/common/tests/test_app_filters.py, developerportal/templatetags/app_filters.py
This changeset refactors `app_filters.domain_from_url`, which produces a _display_ string of the hostname for the target URL for a card link, in some situations (eg the 'What we're developing' section on https://developer.mozilla.com/topics/av1-video/)
We now use Wagtail's own lookup function to get a fallback domain hostname, rather than just pull it from HTTP headers.
This 
a) is less trusting of whatever value is in the header and only show a hostname if it's one we're expecting to (ie, it matches a configured Site in Django/Wagtail)
and
b) ensures that we show and use the configured site's hostname (ie the CDN hostname) not the hostname of the CMS in rendered pages (because this is the value that's configured in the Site record)
- Code review is probably enough here, as there are also …
=> 1625: Minor refactor to domain_from_url helper

developerportal/apps/common/tests/test_app_tags.py, developerportal/apps/topics/migrations/0053_update_streamblock.py, developerportal/apps/topics/models.py, developerportal/templates/organisms/featured.html, developerportal/templatetags/app_tags.py
This changeset addresses a need to be able to show more than five featured items on a `Topic` page. 
It now allows up to seven, including six.
This change only applies to the Topic page, but it would be easy enough to use on the Homepage and Events page, if need be, simply by increasing the maximum allowed in the editor (a two-character code change).
The previous layout patterns are still supported, with the same results as prior to the refactor
(Related issue #1623)
- Refactored Django tempate tag that splits up a list of _n_ pages into (effectively) a list of sub-lists, with one sub-list for each row, including an explicit count of items in each row
- Refactored "featured items" HTML component to support up to four items in a row
- Generally the Python and HTML code are cleaner and less …
=> 1623: Support more featured items in topics

developerportal/apps/search/templates/site-search.html, developerportal/templates/header.html, developerportal/templates/molecules/site-search-form.html, src/css/index.scss, src/css/molecules/header.scss, src/css/molecules/site-search-form.scss, src/css/templates/site-search.scss
This changeset builds on PR https://github.com/mdn/developer-portal/pull/1624 to add a search input in the main nav
(Related issue #1453)
- Added search input to main nav: 
- Refactored the site search form into its own component, then re-used in the site nav.
- Mobile and desktop breakpoints well supported. 
- Medium breakpoint is tolerable, but the nav reflow breaks at certain seams.
- Hide the search input on the results page on all views except mobile/smallest viewport:
- To avoid the duplication of the search input when on the results page (ie, in main page and in nav), I've taken a cue from MDN and we no longer show the search input beside the search results in desktop mode, but we DO show the input with the results at mobile viewport width.)
- Cross-browser tested
- HTML validated …
=> 1453: Add search input in nav

locust/README.md, locust/docker-compose.yml, locust/locustfile.py
This changeset adds support for using Locust (https://locust.io) as a convenient way to load test the developer portal.
The approach used is a Dockerized solution (from a pre-built container: https://hub.docker.com/r/locustio/locust) which spins up a lead and worker nodes to increase the number of connections a single local machine can make.
If we want to take things further, we could try a Lambda-based Locust runner.
TLDR: I think we're fine for now.
* Dev deployment, with two small pods for `app`
- 100 concurrent users, hatched at 3/sec
- Without CDN: sustained ~42 requests per second (RPS) and no saturation issues
- with CDN: reached ~100 RPS and no saturation issues
- 250 concurrent users, hatched at 3/sec
- included pagination queries (which will hit the origin until they've been …
=> 1621: Add load-testing tooling and perform initial test

developerportal/apps/home/models.py, developerportal/apps/topics/models.py
This changeset removes the order-by-title logic so that the topics block (used on the homepage and on the /topics/ page, which is live but orphaned) reflects the order of the Topic pages in the Wagtail admin
However, note that because the nav is a two-column vertical list of Topics and the topics block is a four-column horizontal list, we can't make the topics-block items appear in the same horizontal and vertical positioning/ordering as in the nav. (At least not without a HTML/CSS refactor or some extra Python logic.) So, for now the next-best-fit solution is simply to use the "top-down" ordering of the pages in the Wagtail admin as a left-to-right then top-down order (which is the natural flow of the grid)
- Code is on staging for review and test drive. The ordering of the topics on the …
=> 1679: Make Products & Technologies block follow the ordering of items in the nav

developerportal/templates/molecules/navigation/promotion.html
This changeset swaps the ordering of the two promo card/links to the right side of the fold-down sub-menus of the navigation.
Now, the Products & Technologies nav sub-menu contains an MDN Promo instead of a FF Developer one, and the Communities one contains FF Developer not MDN.
- Code is on Staging. Please take a look and confirm whether you're happy with the result. 
(IMO, neither Firefox Develeopr edition nor MDN are particuarly 'at home' in Communities, but that's personal opinion)
=> 1612: Swap order of promos in nav

developerportal/apps/events/templates/events.html, developerportal/templates/molecules/quarter-page-item.html, developerportal/templates/organisms/four-card-row.html
The only place Events can currently be featured is on the Events page, so this changeset adds a new boolean possible in the four-card-row unit to handle this option, and the triggering boolean value is passed down from the parent events.html template
The four-card-row.html logic is getting a bit busy, so refactoring it is worthwhile when we have a bit more time on our hands.
(Related issue #1662)
- Code is on its way to Staging, where you can check this change
- confirm featured events show dates
- confirm "What we're working on" on topics still shows domain names (because this it uses the HTML unit we've updated in this changeset)
=> 1662: Ensure featured events show their dates

developerportal/apps/common/constants.py, developerportal/apps/common/utils.py, developerportal/apps/ingestion/tests/test_utils.py, developerportal/apps/ingestion/utils.py
This changeset tightens up the sanitisation of input strings we acquire from specific, explicitly-configured RSS and Atom feeds, which are then used to make draft pages. While the pages are manually checked before publication, it's still good to strip out as many potentially bad substrings as possible, even though the odds of the source feeds being bad themselves is low.
This work was done as part of pre-hard-launch hardening.
(Related issue #1609)
- improve cleanup of description strings
- add cleanup of title strings
- add cleanup of author names
- Code review only. Looking at the tests should guide you through my thinking. Please shout if you thikn there are gaps worth covering
=> 1690: Further tighten ingestion feed processing

k8s/Makefile, k8s/app.env.yaml.j2, k8s/config/stage.sh
This changeset allows us to disable rate limiting via k8s config, and does this (temporarily) for stage to show it works.
- Try to make more than 30 requests against stage in 60 seconds and it WILL currenlty be allowed
=> Add support for enabling/disabling rate-limiting via env var

Jenkinsfile, k8s/Makefile, k8s/redirector.deployment.yaml.j2, k8s/redirector.ingress.yaml.j2, k8s/redirector.svc.yaml.j2
This creates a redirect service for the developer-portal app, its a simple nginx ingress that redirects traffic for www.mozilla.dev to mozilla.dev as well as developer.mozilla.com to mozilla.dev
(Related issue https://github.com/mdn/infra/issues/452)
- Adds a redirect service for developer-portal
=> Redirect service

src/css/molecules/site-search-form.scss
This changeset allows us to override the default styling of a `search` input in Safari (which is already allowed in all other target browsers)
Before, in Safari:
After:
Also in iOS (emulation):
- Code is on [stage](https://developer-portal.stage.mdn.mozit.cloud). I've cross-browser tested, but another pair of eyes is very welcome
=> Hotfix: make Safari allow styling of the search input in the main nav

developerportal/templates/base.html, developerportal/templates/header.html, developerportal/templates/molecules/accessibility-nav.html, src/css/index.scss, src/css/molecules/accessibility-nav.scss, src/css/molecules/header.scss
This changeset addresses a11y issues with the main nav spotted by @schalkneethling (thanks!)
* remove unnecessary <img>
* SCSS cleanup
* add quick-access nav links
Note that one recommendation from the source ticket #1709 was do drop a base-64 data-uri image from the CSS, but it looks like this was actually needed as the close trigger for the nav when in mobile-viewport mode.
- Code will be on [staging](https://developer-portal.stage.mdn.mozit.cloud/) by the time you read this
=> 1709: Header a11y improvements

developerportal/templates/organisms/featured.html
This changeset removes all divs from the markup in favour of unordered lists. Now have a list of sublists, which represents both how the content is structured in terms of heirarchy and still flows appropriately.
(Related issue #1719)
- Code is deployed to stage and you can see it on the Homepage and on any page in Products & Technologies
=> 1719: Improve markup of Featured Items component for improved a11y

developerportal/apps/home/templates/home.html, developerportal/apps/topics/templates/topics.html, developerportal/templates/molecules/item-topic-link.html, developerportal/templates/organisms/homepage-about.html, developerportal/templates/organisms/topic-links.html, src/css/index.scss, src/css/molecules/item-topic-link.scss, src/css/organisms/topic-links.scss
This changeset contains markup improvements to boost a11y, as suggested in #1720.
- Code is being deployed to staging, so please check it out there. 
- There are three places the topics component is used:
- homepage
- /topics/
- on a Person page, where they are associated with one or more topics/technologies. In this situation, the topics component renders its output as a two-column layout over four grid columns, not four cols over four.
=> 1720: Topics component a11y improvements

developerportal/apps/articles/templates/articles.html
This one-item changeset contains a small markup improvement to the /articles/ page, adding a `main` node with the appropriate role attribute
This, when combined with the work done for #1723 in PR #1761 completes the work outlined in the ticket #1722
- code will be on staging
=> [1722] Add main element to articles listing page

package-lock.json
https://www.npmjs.com/advisories/1179
For some reason npm audit fix and nmp update did not resolve the issues, so doing it manually seemed the next best workable approach
The static container now builds with 1.2.5 everywhere
/app # npm ls | grep minimist
| +-- minimist@1.2.5
|     `-- minimist@1.2.5
| |   `-- minimist@1.2.5
| | `-- minimist@1.2.5
|   | `-- minimist@1.2.5 deduped
|   +-- minimist@1.2.5 deduped
| | | | | `-- minimist@1.2.5 deduped
| | | | | `-- minimist@1.2.5 deduped
| | | | +-- minimist@1.2.5 deduped
npm| | +-- minimist@1.2.5 deduped
ERR! missing: bindings@^1.5.0, required by fsevents@1.2.13
| |   `-- minimist@1.2.5
| |   `-- minimist@1.2.5 deduped
=> Manually bump minimist dependency to 1.2.5 following NPM audit warning

developerportal/apps/events/templates/events.html, developerportal/apps/home/templates/home.html, developerportal/apps/people/templates/people.html, developerportal/apps/topics/templates/topic.html
This changeset fixes up a markup glitch where the Newsletter component (which is in an <aside> was placed inside a <main> component.
- Events page
- Homepage
- People page
- Topic page
(Resolves #1759)
- code is on its way to staging
=> [1759] Move newsletter <aside> out of <main> on a few pages

developerportal/apps/articles/templates/article.html, developerportal/templates/molecules/cards/card-person.html, developerportal/templates/organisms/people-section.html, src/css/organisms/people-section.scss, src/css/templates/article.scss
Related to changes to the topic page requested in #1735, this changeset completes the acceptance criteria by fixing up the People section - eg see https://developer-portal.stage.mdn.mozit.cloud/topics/av1-video/
It also slides in a small change to the Article page, which also uses the parital/component updated in this PR.
- 1735: Update markup for "People section" component to have better a11y
* Fix up heading heirarchy
* Make items a list not div soup
* Make card-person.html take an explicitly nominated HTML element to use as its wrapping element, defaulting to div -- this is because the template partial is used now in a list but also elsewhere as a single standalone item, which doesn't make sense to mark up as a list
- 1753: Update use of people-section on the Article page, to improve …
=> 1735: Update people section markup

developerportal/apps/common/middleware.py, developerportal/apps/common/tests/test_middleware.py, developerportal/settings/base.py
This changeset updates the ratelimiting middleware to apply a less strict limit on requests made by authenticated staff users (ie, those with Wagtail CMS access). This is so that things like the image search typeahead isn't blocked so readily.
The initial value for the admin-user rate limiting is now 60 requests per minute, up from 25 per minute (which remains the default for unauthenticated users).
Note that the user has to be both authenticated AND a staff/admin user to not be treated as a regular public user. At the moment, all our authenticated users are staff, but this may not always be the case.
Tests have been extended to prove this is working as expected, plus manual checks have been done, but it's still possible that we need to increase the admin-user limit further, or simply …
=> 1751: Extend app-level ratelimiting so that admin/CMS editors get a higher threshold

developerportal/templates/molecules/pagination.html, src/css/molecules/pagination.scss
This changeset fixes up the wording of the pagination "Prev" button to be "Previous"
It also adds `min-width` values, where smallest viewport has _something_ useful to make the buttons look a bit more balanced in terms of size, while larger sizes have a min-width that ensures consistent button sizing
Note that the layout breaks a little when the viewport is smaller than 360px.
(Related issue #1734)
- Code will be on staging
=> 1734: Amend wording of Prev button to Previous

developerportal/templates/molecules/quarter-page-item.html, developerportal/templates/organisms/four-card-row.html, src/css/organisms/four-card-row.scss
This changeset addresses some a11y-related markup issues in the 'Related items' panel on an Event detail page, which is actually the 'four-card-row' component used in a number of places in the site, such as the 'Featured events' block on the /events/ page and the 'What we are working on' panel on a Topic page
- Code is on Staging. Please see #1736 for the acceptance criteria
=> 1736: Event page - a11y improvements to four-card-row component

developerportal/apps/common/templates/button_block.html, developerportal/apps/common/wagtail_hooks.py, developerportal/templates/molecules/card-featured.html, developerportal/templates/molecules/cards/card-article.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/molecules/quarter-page-item.html, developerportal/templates/molecules/resource-share.html, developerportal/templates/molecules/search-result.html, developerportal/templates/organisms/newsletter-signup.html, developerportal/templates/survey.html, src/js/tests/newsletter-subscription.test.js, src/js/tests/task-completion-prompt.test.js
For links that use `target="_blank"` we already had `rel="noopener"` set and sometimes `nofollow` and sometimes `noreferrer`, but this changeset brings them all into line so that ALL of them use `nofollow noreferrer noopener` for consistency and predictability. (I've also seen this pattern used by Mozilla Hacks blog.)
This does raise questions about SEO and analytics, regarding `nofollow` and `noreferer` and we could in the future support fine-grained control over those values for links.
Please feel free to disagree!
(Related issue #1758)
- code will be on staging soon, so look at external links or social sharing links. However, what's more important is consensus on whether `nofollow` is definitely worth it and whether we are comfortable with/without `noreferrer`
=> 1758: Ensure all external links have the same values for the rel attribute

developerportal/apps/common/tests/test_app_tags.py, developerportal/apps/videos/templates/video.html, developerportal/templatetags/app_tags.py, src/css/atoms/embed.scss
This changeset improves the accessibility of embedded videos and fixes an overlooked HTML validation error.
(Related issue #1741)
* Adds a `title` attribute to the iframe, based on the page title, but only if there is not already a title present
* Drops the now-deprecated `frameborder` attribute, instead using CSS to ensure the iframe has no border
**Example:**
BEFORE
```    <iframe width="480" height="270" src="https://www.youtube.com/embed/xTH0hb1nYoE?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>```
AFTER:
```    <iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" height="270" src="https://www.youtube.com/embed/xTH0hb1nYoE?feature=oembed" …
```
=> 1741: Make rendering of iframed video embeds better in the Video page

developerportal/apps/articles/templates/article.html, developerportal/apps/articles/templates/articles.html, developerportal/apps/events/templates/event.html, developerportal/apps/people/templates/person.html, developerportal/templates/molecules/cards/card-article.html, developerportal/templates/molecules/cards/card-event.html, developerportal/templates/molecules/cards/card-person.html, developerportal/templates/molecules/cards/card-video.html, developerportal/templates/molecules/cards/card.html, developerportal/templates/organisms/filter-list.html, developerportal/templates/organisms/people-section.html
This changeset moves the filter-list component (used on /posts/, /events/ and /people/communities/ to mark up the results cards as a list, not div soup.
As a knock-on from that, there are a few places where the cards (which now default to using an li as their root node) need specifying to use a div instead of an li as their root nodes.
This changeset will overlap slightly with some of the work for PR#1749, but I'll deal with that in the merge once it's all signed off.
- Code will be on Staging
=> [1723] Improve filter-list markup

developerportal/apps/home/models.py, developerportal/templates/organisms/homepage-header.html
This changeset addresses duplicated content in the header of the hompage, following one of the recommendations in the ticket
(Related issue #1718)
- Code is deployed to  [staging](developer-portal.stage.mdn.mozit.cloud/)
=> 1718 hero unit a11y improvements
